
import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useToast } from '../hooks/use-toast';
import axios from 'axios';
import { useLanguage } from '../contexts/LanguageContext';
import { 
  FileText, Download, Filter, Eye, Plus, 
  CheckCircle, Clock, AlertCircle, CreditCard,
  RotateCcw, History
} from 'lucide-react';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const statusColors = {
  draft: 'bg-gray-100 text-gray-800',
  issued: 'bg-blue-100 text-blue-800',
  paid: 'bg-emerald-100 text-emerald-800',
  cancelled: 'bg-rose-100 text-rose-800',
  overdue: 'bg-amber-100 text-amber-800',
  refunded: 'bg-purple-100 text-purple-800',
  partially_refunded: 'bg-purple-50 text-purple-700',
};

export default function Invoices() {
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ country: '', status: '' });
  const [selectedInvoice, setSelectedInvoice] = useState(null);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showRefundModal, setShowRefundModal] = useState(false);
  
  const [searchParams, setSearchParams] = useSearchParams();
  const { toast } = useToast();

  useEffect(() => {
    const paymentStatus = searchParams.get('payment');
    if (paymentStatus === 'success') {
      toast({
        title: "Payment Successful",
        description: "The invoice has been marked as paid.",
        variant: "success"
      });
      // Clear params
      setSearchParams({});
    } else if (paymentStatus === 'cancelled') {
      toast({
        title: "Payment Cancelled",
        description: "The payment process was cancelled.",
        variant: "destructive"
      });
      setSearchParams({});
    }
  }, [searchParams]);

  useEffect(() => {
    fetchInvoices();
  }, [filters]);

  const fetchInvoices = async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams();
      if (filters.country) params.append('country', filters.country);
      if (filters.status) params.append('status', filters.status);
      const response = await axios.get(`${API}/invoices?${params}`);
      setInvoices(response.data);
    } catch (error) {
      console.error('Failed to fetch invoices:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateInvoice = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const items = [{
      description: formData.get('item_desc'),
      quantity: 1,
      unit_price: parseFloat(formData.get('amount'))
    }];

    const data = {
      country: formData.get('country'),
      customer_type: 'B2C',
      customer_name: formData.get('customer_name'),
      customer_email: formData.get('customer_email'),
      customer_ref_id: null, // Will be generated by backend
      items: items
    };

    try {
      await axios.post(`${API}/invoices`, data);
      setShowCreateModal(false);
      fetchInvoices();
    } catch (error) {
      alert(error.response?.data?.detail || 'Error creating invoice');
    }
  };

  const handlePay = async (invoiceId) => {
    try {
      const response = await axios.post(`${API}/payments/invoices/${invoiceId}/checkout`, {
        success_url: window.location.origin + "/invoices",
        cancel_url: window.location.origin + "/invoices"
      });
      if (response.data.checkout_url) {
        window.location.href = response.data.checkout_url;
      }
    } catch (error) {
      alert(error.response?.data?.detail || 'Payment initiation failed');
    }
  };

  const handleRefund = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const amount = parseFloat(formData.get('amount'));
    const reason = formData.get('reason');

    if (!selectedInvoice) return;

    try {
      await axios.post(`${API}/payments/invoices/${selectedInvoice.id}/refund`, {
        amount,
        reason
      });
      setShowRefundModal(false);
      // Refresh invoice detail
      viewInvoice(selectedInvoice.id);
      fetchInvoices();
      toast({
        title: "Refund Initiated",
        description: "The refund request has been sent to Stripe.",
        variant: "success"
      });
    } catch (error) {
      alert(error.response?.data?.detail || 'Refund failed');
    }
  };

  const viewInvoice = async (id) => {
    try {
      const response = await axios.get(`${API}/invoices/${id}`);
      setSelectedInvoice(response.data);
    } catch (error) {
      console.error('Failed to fetch invoice details:', error);
    }
  };

  return (
    <div className="space-y-6" data-testid="invoices-page">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Invoices</h1>
          <p className="text-muted-foreground text-sm mt-1">
            Billing history and core invoice management
          </p>
        </div>
        <div className="flex gap-2">
          <button className="flex items-center gap-2 px-4 py-2 rounded-md border hover:bg-muted">
            <Download size={16} />
            Export CSV
          </button>
          <button
            onClick={() => setShowCreateModal(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90"
          >
            <Plus size={16} />
            Create Invoice
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex gap-2 p-2 bg-card border rounded-md w-fit">
        <div className="flex items-center px-2 border-r">
          <Filter size={16} className="text-muted-foreground" />
        </div>
        <select 
          value={filters.country}
          onChange={(e) => setFilters({...filters, country: e.target.value})}
          className="bg-transparent border-none text-sm focus:ring-0"
        >
          <option value="">All Countries</option>
          {['DE', 'CH', 'FR', 'AT'].map(c => <option key={c} value={c}>{c}</option>)}
        </select>
        <select 
          value={filters.status}
          onChange={(e) => setFilters({...filters, status: e.target.value})}
          className="bg-transparent border-none text-sm focus:ring-0"
        >
          <option value="">All Statuses</option>
          {Object.keys(statusColors).map(s => <option key={s} value={s}>{s}</option>)}
        </select>
      </div>

      {/* Invoices Table */}
      <div className="bg-card rounded-md border overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b bg-muted/50 text-left">
              <th className="p-4 font-medium">Invoice #</th>
              <th className="p-4 font-medium">Customer</th>
              <th className="p-4 font-medium">Date</th>
              <th className="p-4 font-medium">Amount</th>
              <th className="p-4 font-medium">Status</th>
              <th className="p-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={6} className="p-8 text-center">Loading...</td></tr>
            ) : invoices.length === 0 ? (
              <tr><td colSpan={6} className="p-8 text-center text-muted-foreground">No invoices found</td></tr>
            ) : (
              invoices.map((inv) => (
                <tr key={inv.id} className="border-b last:border-0 hover:bg-muted/50">
                  <td className="p-4 font-medium">{inv.invoice_no}</td>
                  <td className="p-4">
                    <div className="font-medium">{inv.customer_name}</div>
                    <div className="text-xs text-muted-foreground">{inv.customer_type}</div>
                  </td>
                  <td className="p-4 text-muted-foreground">
                    {new Date(inv.issued_at).toLocaleDateString()}
                  </td>
                  <td className="p-4 font-medium">
                    {inv.gross_total.toLocaleString()} {inv.currency}
                  </td>
                  <td className="p-4">
                    <span className={`px-2 py-1 rounded-full text-xs font-medium capitalize ${statusColors[inv.status] || 'bg-gray-100'}`}>
                      {inv.status}
                    </span>
                  </td>
                  <td className="p-4 text-right">
                    <div className="flex justify-end gap-1">
                      {inv.status === 'draft' && (
                        <button
                          onClick={() => handlePay(inv.id)}
                          className="p-2 hover:bg-emerald-100 text-emerald-600 rounded-md"
                          title="Pay with Stripe"
                        >
                          <CreditCard size={16} />
                        </button>
                      )}
                      <button 
                        onClick={() => viewInvoice(inv.id)}
                        className="p-2 hover:bg-muted rounded-md"
                      >
                        <Eye size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Detail Modal */}
      {selectedInvoice && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-card rounded-lg border shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto p-6">
            <div className="flex justify-between items-start mb-6 border-b pb-4">
              <div>
                <h2 className="text-xl font-bold">{selectedInvoice.invoice_no}</h2>
                <p className="text-sm text-muted-foreground">Issued: {new Date(selectedInvoice.issued_at).toLocaleString()}</p>
              </div>
              <button onClick={() => setSelectedInvoice(null)} className="text-muted-foreground hover:text-foreground">
                Close
              </button>
            </div>

            <div className="grid grid-cols-2 gap-8 mb-8">
              <div>
                <h3 className="font-semibold mb-2 text-sm text-muted-foreground uppercase">Billed To</h3>
                <div className="font-medium">{selectedInvoice.customer_name}</div>
                <div className="text-sm">{selectedInvoice.customer_email}</div>
                <div className="text-sm mt-1">{selectedInvoice.customer_address}</div>
                {selectedInvoice.customer_vat_no && <div className="text-sm mt-1">VAT: {selectedInvoice.customer_vat_no}</div>}
              </div>
              <div className="text-right">
                <h3 className="font-semibold mb-2 text-sm text-muted-foreground uppercase">Payment Details</h3>
                <div className="text-2xl font-bold">{selectedInvoice.gross_total.toLocaleString()} {selectedInvoice.currency}</div>
                <div className={`inline-block mt-2 px-3 py-1 rounded-full text-sm font-medium capitalize ${statusColors[selectedInvoice.status]}`}>
                  {selectedInvoice.status}
                </div>
              </div>
            </div>

            {/* Refund Section */}
            {(selectedInvoice.status === 'paid' || selectedInvoice.status === 'partially_refunded') && (
              <div className="mb-8 border-t pt-4">
                <div className="flex justify-between items-center mb-4">
                  <h3 className="font-semibold text-sm text-muted-foreground uppercase">Refunds</h3>
                  <button 
                    onClick={() => setShowRefundModal(true)}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-md border text-sm hover:bg-muted"
                  >
                    <RotateCcw size={14} />
                    Refund Transaction
                  </button>
                </div>
                
                {selectedInvoice.refunded_total > 0 && (
                  <div className="bg-purple-50 p-3 rounded-md border border-purple-100 mb-4">
                    <div className="flex justify-between text-sm font-medium text-purple-900">
                      <span>Total Refunded</span>
                      <span>{selectedInvoice.refunded_total} {selectedInvoice.currency}</span>
                    </div>
                  </div>
                )}
              </div>
            )}

            <table className="w-full mb-8">
              <thead>
                <tr className="border-b text-sm text-muted-foreground">
                  <th className="text-left py-2">Description</th>
                  <th className="text-right py-2">Qty</th>
                  <th className="text-right py-2">Unit Price</th>
                  <th className="text-right py-2">Total</th>
                </tr>
              </thead>
              <tbody>
                {selectedInvoice.items.map(item => (
                  <tr key={item.id} className="border-b last:border-0">
                    <td className="py-3">{typeof item.description === 'string' ? item.description : JSON.stringify(item.description)}</td>
                    <td className="py-3 text-right">{item.quantity}</td>
                    <td className="py-3 text-right">{item.unit_price_net}</td>
                    <td className="py-3 text-right font-medium">{item.line_net}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <div className="flex justify-end">
              <div className="w-48 space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Subtotal</span>
                  <span>{selectedInvoice.net_total} {selectedInvoice.currency}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">VAT ({selectedInvoice.tax_rate_snapshot}%)</span>
                  <span>{selectedInvoice.tax_total} {selectedInvoice.currency}</span>
                </div>
                <div className="flex justify-between font-bold border-t pt-2">
                  <span>Total</span>
                  <span>{selectedInvoice.gross_total} {selectedInvoice.currency}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Create Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-card rounded-lg border shadow-xl w-full max-w-md p-6">
            <h2 className="text-lg font-bold mb-4">Create Manual Invoice</h2>
            <form onSubmit={handleCreateInvoice} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-1">Country</label>
                  <select name="country" className="w-full rounded-md border px-3 py-2 bg-background">
                    <option value="DE">Germany</option>
                    <option value="CH">Switzerland</option>
                    <option value="FR">France</option>
                    <option value="AT">Austria</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium mb-1">Amount</label>
                  <input type="number" name="amount" className="w-full rounded-md border px-3 py-2 bg-background" required />
                </div>
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Customer Name</label>
                <input name="customer_name" className="w-full rounded-md border px-3 py-2 bg-background" required />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Customer Email</label>
                <input type="email" name="customer_email" className="w-full rounded-md border px-3 py-2 bg-background" required />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Item Description</label>
                <input name="item_desc" className="w-full rounded-md border px-3 py-2 bg-background" required />
              </div>

              <div className="flex gap-2 justify-end pt-4">
                <button type="button" onClick={() => setShowCreateModal(false)} className="px-4 py-2 rounded-md hover:bg-muted">Cancel</button>
                <button type="submit" className="px-4 py-2 rounded-md bg-primary text-primary-foreground">Create</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Refund Modal */}
      {showRefundModal && selectedInvoice && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-card rounded-lg border shadow-xl w-full max-w-sm p-6">
            <h2 className="text-lg font-bold mb-4">Refund Invoice</h2>
            <p className="text-sm text-muted-foreground mb-4">
              Processing refund for invoice {selectedInvoice.invoice_no}.
              Max refundable: {selectedInvoice.net_total + selectedInvoice.tax_total - (selectedInvoice.refunded_total || 0)} {selectedInvoice.currency}
            </p>
            <form onSubmit={handleRefund} className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Refund Amount</label>
                <input 
                  type="number" 
                  step="0.01" 
                  name="amount" 
                  defaultValue={selectedInvoice.net_total + selectedInvoice.tax_total - (selectedInvoice.refunded_total || 0)}
                  max={selectedInvoice.net_total + selectedInvoice.tax_total - (selectedInvoice.refunded_total || 0)}
                  className="w-full rounded-md border px-3 py-2 bg-background" 
                  required 
                />
              </div>
              
              <div>
                <label className="block text-sm font-medium mb-1">Reason</label>
                <select name="reason" className="w-full rounded-md border px-3 py-2 bg-background">
                  <option value="requested_by_customer">Requested by Customer</option>
                  <option value="duplicate">Duplicate Charge</option>
                  <option value="fraudulent">Fraudulent</option>
                </select>
              </div>

              <div className="flex gap-2 justify-end pt-4">
                <button type="button" onClick={() => setShowRefundModal(false)} className="px-4 py-2 rounded-md hover:bg-muted">Cancel</button>
                <button type="submit" className="px-4 py-2 rounded-md bg-rose-600 text-white hover:bg-rose-700">Process Refund</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
