import { createContext, useContext, useState, useEffect } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const translations = {
  tr: {
    // Common
    dashboard: 'Kontrol Paneli',
    users: 'Kullanıcılar',
    countries: 'Ülkeler',
    feature_flags: 'Özellik Bayrakları',
    audit_logs: 'Denetim Kayıtları',
    settings: 'Ayarlar',
    logout: 'Çıkış',
    login: 'Giriş',
    email: 'E-posta',
    password: 'Şifre',
    submit: 'Gönder',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    create: 'Oluştur',
    search: 'Ara',
    filter: 'Filtre',
    all: 'Tümü',
    active: 'Aktif',
    inactive: 'Pasif',
    enabled: 'Etkin',
    disabled: 'Devre Dışı',
    actions: 'İşlemler',
    status: 'Durum',
    name: 'Ad',
    role: 'Rol',
    created_at: 'Oluşturulma',
    updated_at: 'Güncelleme',
    // Dashboard
    total_users: 'Toplam Kullanıcı',
    active_users: 'Aktif Kullanıcı',
    enabled_countries: 'Aktif Ülke',
    enabled_features: 'Aktif Özellik',
    recent_activity: 'Son Aktivite',
    // Roles
    super_admin: 'Süper Admin',
    country_admin: 'Ülke Admin',
    moderator: 'Moderatör',
    support: 'Destek',
    finance: 'Finans',
    // Feature Flags
    module: 'Modül',
    feature: 'Özellik',
    enabled_countries: 'Aktif Ülkeler',
    toggle: 'Aç/Kapa',
    // Auth
    welcome_back: 'Tekrar Hoşgeldiniz',
    login_subtitle: 'Admin paneline erişmek için giriş yapın',
    // Messages
    login_success: 'Giriş başarılı',
    login_error: 'Giriş başarısız',
    save_success: 'Kaydedildi',
    delete_success: 'Silindi',
    // Portals
    portal_consumer: 'Bireysel Portal',
    portal_dealer: 'Ticari Portal',
    nav_section: 'Menü',
    nav_listings: 'İlan Yönetimi',
    nav_favorites: 'Favoriler',
    nav_messages: 'Mesajlar & Bildirimler',
    nav_services: 'Servisler',
    nav_account: 'Hesabım',
    nav_dashboard: 'Özet',
    nav_my_listings: 'İlanlarım',
    nav_create_listing: 'Yeni İlan',
    nav_support: 'Destek Talepleri',
    nav_profile: 'Profil',
    nav_privacy_center: 'Gizlilik Merkezi',
    nav_favorite_listings: 'Favori İlanlar',
    nav_invoices: 'Faturalar',
    nav_company: 'Şirket',
    nav_dealer_dashboard: 'Panel',
    nav_overview: 'Özet',
    nav_active_listings: 'Yayındaki İlanlar',
    nav_draft_listings: 'Taslaklar',
    nav_archived_listings: 'Arşiv',
    nav_favorite_searches: 'Favori Aramalar',
    nav_inbox: 'Gelen Kutusu',
    nav_notifications: 'Bildirimler',
    nav_support_center: 'Destek Merkezi',
    nav_security: 'Güvenlik',
    nav_data_export: 'Veri Dışa Aktarım',
    nav_account_delete: 'Hesap Silme',
    nav_permissions: 'İzinler',
    nav_plan_quota: 'Plan ve Kota',
    nav_billing_overview: 'Faturalandırma Özeti',
    nav_invoice_history: 'Fatura Geçmişi',
    nav_payment_methods: 'Ödeme Yöntemleri',
    nav_company_team: 'Ekip ve Yetkiler',
    nav_company_branches: 'Şubeler',
    portal_demo_title: 'Portal Önizleme',
    portal_demo_subtitle: 'Avrupa standartlarında menü yapısı ve GDPR odakları.',
    portal_demo_consumer: 'Bireysel',
    portal_demo_dealer: 'Ticari',
    portal_demo_consumer_title: 'Bireysel Kontrol Alanı',
    portal_demo_dealer_title: 'Ticari Kontrol Alanı',
    portal_demo_gdpr_title: 'GDPR Güvenlik Notu',
    portal_demo_gdpr_text: 'Veri erişimi, dışa aktarma ve hesap silme adımları gizlilik merkezinden yönetilir.',
    card_active_listings: 'Yayındaki İlan',
    card_favorites: 'Favori',
    card_messages: 'Mesaj',
    card_quota: 'Kota Kullanımı',
    card_balance: 'Fatura Toplamı',
    header_user_fallback: 'Kullanıcı',
    header_search_placeholder: 'Arama yap',
    header_suggestions_loading: 'Öneriler yükleniyor…',
    header_create_listing: 'İlan Ver',
    header_login: 'Giriş Yap',
    header_register: 'Üye Ol',
    header_messages: 'Mesajlar',
    header_notifications: 'Bildirimler',
    header_favorites: 'Favoriler',
    header_profile: 'Profil',
    header_settings: 'Ayarlar',
    header_logout: 'Çıkış',
    admin_header_title: 'Header Yönetimi',
    admin_header_subtitle: 'Guest, authenticated ve kurumsal header içeriğini yönetin.',
    admin_header_upload_hint: 'Maksimum logo boyutu:',
    admin_header_upload_button: 'Logo Yükle',
    admin_header_save_button: 'Header Değişikliklerini Kaydet',
    admin_header_saving: 'Kaydediliyor...',
    admin_header_saved: 'Header yapılandırması kaydedildi.',
    admin_header_save_error: 'Header kaydedilemedi',
    admin_header_logo_updated: 'Logo güncellendi',
    admin_header_upload_error: 'Logo yükleme başarısız',
    admin_header_select_file: 'Dosya seçin',
    admin_header_links_title: 'Link Yönetimi',
    admin_header_add_link: 'Link Ekle',
    admin_header_links_empty: 'Bu header için link bulunmuyor.',
    admin_header_link_label_placeholder: 'Link etiketi',
    admin_header_link_url_placeholder: 'URL (örn: /search)',
    auth: {
      login: {
        info_banner: "Avrupa'nın en yeni ve geniş ilan platformu Annoncia'ya hoş geldiniz. Hesabınız yoksa ücretsiz hesap açabilirsiniz.",
        title: 'Giriş yap',
        subtitle: 'Hesabınıza giriş yapın.',
        portal_type: 'Giriş türü',
        portal_account: 'Bireysel',
        portal_dealer: 'Ticari',
        email_placeholder: 'E-posta adresi',
        password_placeholder: 'Şifre',
        remember_me: 'Oturumum açık kalsın',
        forgot_password: 'Şifremi unuttum',
        submit: 'E-posta ile giriş yap',
        submit_loading: 'Yükleniyor...',
        no_account: 'Henüz hesabın yok mu?',
        create_account: 'Hesap aç',
        or: 'VEYA',
        google_soon: 'Google ile giriş yap (Yakında)',
        apple_soon: 'Apple ile giriş yap (Yakında)',
        qr_login: 'QR kod ile mobil uygulamadan giriş yap',
        totp_label: '2FA Kodu',
        totp_placeholder: '6 haneli doğrulama kodu',
        totp_help: 'Authenticator uygulamanızdaki kodu girin.',
        admin: {
          session_verified: 'Oturum doğrulandı',
          loading_panel: 'Admin paneli yükleniyor...',
        },
        errors: {
          invalid_credentials: 'E-posta veya şifre hatalı',
          invalid_totp: 'Doğrulama kodu hatalı',
          totp_required: '2FA doğrulama kodu gerekli',
          totp_setup_incomplete: '2FA kurulumu tamamlanmamış',
          account_deleted: 'Hesap silinmiş',
          account_suspended: 'Hesap askıya alınmış',
          rate_limited: 'Çok fazla deneme yaptınız. 15 dakika sonra tekrar deneyin.',
          email_not_verified: 'Hesabınızı doğrulamanız gerekiyor.',
          unknown: 'Giriş başarısız. Lütfen tekrar deneyin.',
          send_verification: 'Doğrulama kodu gönder',
          temp_locked: 'Güvenlik nedeniyle geçici olarak engellendi.',
          account_locked_help: 'Hesap kilitlendi mi?',
          portal_mismatch_admin: 'Bu hesap yönetici hesabı. Lütfen admin girişini kullanın.',
          portal_mismatch_account: 'Bu hesap bireysel giriş içindir. Bireysel seçimini kullanın.',
          portal_mismatch_dealer: 'Bu hesap ticari giriş içindir. Ticari seçimini kullanın.',
        },
      },
      register: {
        title_dealer: 'Ticari Kayıt',
        title_individual: 'Bireysel Kayıt',
        subtitle: 'Bilgilerinizi girerek hesabınızı oluşturun.',
        verify_banner: 'Mail doğrulama kodu gönderildi. Lütfen 6 haneli kodu girin.',
        company_name: 'Firma adı',
        contact_name: 'Yetkili kişi',
        full_name: 'Ad Soyad',
        country: 'Ülke',
        select_country: 'Ülke seçin',
        countries_loading: 'Ülkeler yükleniyor...',
        tax_optional: 'Vergi / ID (opsiyonel)',
        submit: 'Hesap Oluştur',
        submit_loading: 'Kaydediliyor...',
        code_label: 'Doğrulama kodu',
        attempts_left: 'Kalan deneme: {{count}}',
        verify_submit: 'Doğrula',
        verify_loading: 'Doğrulanıyor...',
        resend_code: 'Kodu tekrar gönder',
        resend_code_with_timer: 'Kodu tekrar gönder ({{seconds}}s)',
        back_to_login: 'Girişe dön',
        already_have_account: 'Zaten hesabın var mı?',
        login: 'Giriş yap',
        company_name_placeholder: 'Örn: Annoncia Motors',
        contact_name_placeholder: 'Örn: Ayşe Yılmaz',
        full_name_placeholder: 'Örn: Ali Demir',
        email_placeholder: 'mail@ornek.com',
        password_placeholder: 'En az 8 karakter',
        tax_placeholder: 'Vergi numarası',
        toast: {
          code_sent_title: 'Doğrulama kodu gönderildi',
          code_sent_desc: 'Lütfen e-postanızı kontrol edin.',
          verify_success_title: 'Doğrulama tamamlandı',
          verify_success_desc: 'Hesabınız doğrulandı.',
          code_resent_title: 'Kod yeniden gönderildi',
        },
        errors: {
          countries_failed: 'Ülkeler yüklenemedi',
          country_list_fallback: 'Ülke listesi yüklenemedi. Varsayılan ülke kullanılıyor.',
          company_contact_required: 'Firma adı ve yetkili kişi zorunludur.',
          fullname_required: 'Ad soyad zorunludur.',
          email_required: 'E-posta zorunludur.',
          password_min: 'Şifre en az 8 karakter olmalıdır.',
          country_required: 'Ülke seçimi zorunludur.',
          register_failed: 'Kayıt başarısız',
          code_required: '6 haneli kodu girin.',
          too_many_attempts: 'Çok fazla deneme yapıldı. Lütfen bekleyin.',
          code_invalid: 'Kod doğrulanamadı.',
          resend_wait: 'Kısa süre önce gönderildi. Lütfen bekleyin.',
          code_send_failed: 'Kod gönderilemedi.',
        },
      },
      verify: {
        info_banner: "Avrupa'nın en yeni ve geniş ilan platformu Annoncia'ya hoş geldiniz. Lütfen e-posta doğrulama kodunu girin.",
        title: 'E-posta doğrulama',
        subtitle: '6 haneli kodu girerek hesabınızı doğrulayın.',
        code_label: 'Doğrulama kodu',
        attempts_left: 'Kalan deneme: {{count}}',
        submit: 'Doğrula',
        submit_loading: 'Doğrulanıyor...',
        resend_code: 'Kodu tekrar gönder',
        resend_code_with_timer: 'Kodu tekrar gönder ({{seconds}}s)',
        no_code: 'Kod gelmedi mi?',
        back_to_login: 'Girişe dön',
        help_title: 'Yardım',
        help_spam: 'Spam veya gereksiz klasörünü kontrol edin.',
        help_resend: '90 saniye sonra yeniden gönderme butonunu kullanın.',
        help_support_prefix: 'Sorun devam ederse',
        help_support_link: 'destekle iletişime geçin',
        email_placeholder: 'mail@ornek.com',
        toast: {
          success_title: 'Doğrulama tamamlandı',
          success_desc: 'Hesabınız onaylandı.',
          resent_title: 'Kod yeniden gönderildi',
          sent_desc: 'Lütfen e-postanızı kontrol edin.',
        },
        errors: {
          email_required: 'E-posta zorunludur.',
          code_required: '6 haneli kodu girin.',
          too_many_attempts: 'Çok fazla deneme yapıldı. Lütfen bekleyip tekrar deneyin.',
          code_invalid: 'Kod doğrulanamadı.',
          resend_wait: 'Kısa süre önce gönderildi. Lütfen bekleyin.',
          code_send_failed: 'Kod gönderilemedi.',
        },
      },
    },
    dealer: {
      layout: {
        user_fallback: 'Kurumsal Kullanıcı',
        brand_fallback: 'S Ofisim',
        search_placeholder: 'İlan, müşteri veya rapor ara',
        create_listing: 'İlan Ver',
        quick_action_shortcut: 'Kısayol',
        quick_action_messages: 'Mesajlar',
        profile_settings: 'Profil / Ayarlar',
        logout: 'Çıkış Yap',
        store_filter: 'Mağaza Filtresi',
        all_stores: 'Tümü',
        finish_edit: 'Düzenlemeyi Bitir',
        edit_page: 'Sayfayı Düzenle',
        announcements: 'Duyurular',
        quick_menu_title: 'Kişisel Hızlı Menü',
        quick_menu_edit: 'Düzenle',
        quick_menu_close: 'Kapat',
        quick_menu_recent: 'Son Kullanılanlar',
        quick_menu_favorites: 'Favorilerim',
        quick_menu_empty: 'Bu sekmede öğe yok. Düzenle ile favori ekleyebilirsiniz.',
        quick_menu_search_placeholder: 'Menü ara...',
        menu_fallback_title: 'Menü',
        menu_subtitle: '2. satırdan seçilen menünün alt kırılımları',
        menu_loading: 'Menü yükleniyor…',
      },
      settings: {
        title: 'Hesabım',
        subtitle: 'Hesap bilgileri, güvenlik, ödeme ve bildirim yönetimi.',
        refresh: 'Yenile',
        section_nav_title: 'Hesap bölümleri',
        loading: 'Yükleniyor...',
        save: 'Kaydet',
        save_success_profile: 'Profil bilgileri kaydedildi.',
        save_success_preferences: 'Bildirim tercihleri kaydedildi.',
        security_2fa_active: 'Aktif',
        security_2fa_inactive: 'Pasif',
        security_last_login: 'Son Giriş',
        sections: {
          profile: 'Hesap Bilgileri',
          address: 'Mağaza Bilgileri',
          security: 'Güvenlik',
          store_users: 'Kullanıcı Listesi / Ekle',
          packages_services: 'Paket ve Hizmetler',
          saved_cards: 'Kayıtlı Kartlarım',
          invoices: 'Faturalar',
          account_movements: 'Hesap Hareketleri',
          notifications: 'Bildirim Tercihleri',
          blocked: 'Engellenen Hesaplar',
        },
        security: {
          save_button: 'Güvenlik Bilgilerini Kaydet',
        },
      },
    },
  },
  de: {
    dashboard: 'Dashboard',
    users: 'Benutzer',
    countries: 'Länder',
    feature_flags: 'Feature Flags',
    audit_logs: 'Audit-Protokolle',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    login: 'Anmelden',
    email: 'E-Mail',
    password: 'Passwort',
    submit: 'Absenden',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    create: 'Erstellen',
    search: 'Suchen',
    filter: 'Filter',
    all: 'Alle',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    actions: 'Aktionen',
    status: 'Status',
    name: 'Name',
    role: 'Rolle',
    created_at: 'Erstellt',
    updated_at: 'Aktualisiert',
    total_users: 'Gesamtbenutzer',
    active_users: 'Aktive Benutzer',
    enabled_countries: 'Aktive Länder',
    enabled_features: 'Aktive Features',
    recent_activity: 'Letzte Aktivität',
    super_admin: 'Super Admin',
    country_admin: 'Länder Admin',
    moderator: 'Moderator',
    support: 'Support',
    finance: 'Finanzen',
    module: 'Modul',
    feature: 'Feature',
    toggle: 'Umschalten',
    welcome_back: 'Willkommen zurück',
    login_subtitle: 'Melden Sie sich an, um auf das Admin-Panel zuzugreifen',
    login_success: 'Erfolgreich angemeldet',
    login_error: 'Anmeldung fehlgeschlagen',
    save_success: 'Gespeichert',
    delete_success: 'Gelöscht',
    // Portals
    portal_consumer: 'Privates Portal',
    portal_dealer: 'Gewerbliches Portal',
    nav_section: 'Menü',
    nav_listings: 'Anzeigenverwaltung',
    nav_favorites: 'Favoriten',
    nav_messages: 'Nachrichten & Hinweise',
    nav_services: 'Services',
    nav_account: 'Konto',
    nav_dashboard: 'Übersicht',
    nav_my_listings: 'Meine Anzeigen',
    nav_create_listing: 'Neue Anzeige',
    nav_support: 'Support-Tickets',
    nav_profile: 'Profil',
    nav_privacy_center: 'Datenschutz-Zentrum',
    nav_favorite_listings: 'Favorisierte Anzeigen',
    nav_invoices: 'Rechnungen',
    nav_company: 'Unternehmen',
    nav_company_profile: 'Unternehmensprofil',
    nav_dealer_dashboard: 'Portal-Übersicht',
    nav_overview: 'Übersicht',
    nav_active_listings: 'Aktive Anzeigen',
    nav_draft_listings: 'Entwürfe',
    nav_archived_listings: 'Archiv',
    nav_favorite_searches: 'Favorisierte Suchen',
    nav_inbox: 'Posteingang',
    nav_notifications: 'Benachrichtigungen',
    nav_support_center: 'Support-Zentrum',
    nav_security: 'Sicherheit',
    nav_data_export: 'Datenexport',
    nav_account_delete: 'Konto löschen',
    nav_permissions: 'Einwilligungen',
    nav_plan_quota: 'Plan & Kontingent',
    nav_billing_overview: 'Abrechnungsübersicht',
    nav_invoice_history: 'Rechnungsverlauf',
    nav_payment_methods: 'Zahlungsmethoden',
    nav_company_team: 'Team & Rollen',
    nav_company_branches: 'Filialen',
    portal_demo_title: 'Portal-Vorschau',
    portal_demo_subtitle: 'Menüstruktur nach EU-Standards mit GDPR-Fokus.',
    portal_demo_consumer: 'Privat',
    portal_demo_dealer: 'Gewerblich',
    portal_demo_consumer_title: 'Privater Kontrollbereich',
    portal_demo_dealer_title: 'Gewerblicher Kontrollbereich',
    portal_demo_gdpr_title: 'GDPR Sicherheitshinweis',
    portal_demo_gdpr_text: 'Datenzugriff, Export und Löschung werden im Datenschutz-Zentrum verwaltet.',
    card_active_listings: 'Aktive Anzeigen',
    card_favorites: 'Favoriten',
    card_messages: 'Nachrichten',
    card_quota: 'Kontingent',
    card_balance: 'Rechnungsbetrag',
    header_user_fallback: 'Benutzer',
    header_search_placeholder: 'Suche',
    header_suggestions_loading: 'Vorschläge werden geladen…',
    header_create_listing: 'Anzeige aufgeben',
    header_login: 'Anmelden',
    header_register: 'Registrieren',
    header_messages: 'Nachrichten',
    header_notifications: 'Benachrichtigungen',
    header_favorites: 'Favoriten',
    header_profile: 'Profil',
    header_settings: 'Einstellungen',
    header_logout: 'Abmelden',
    admin_header_title: 'Header-Verwaltung',
    admin_header_subtitle: 'Verwalten Sie Guest-, Auth- und Corporate-Header.',
    admin_header_upload_hint: 'Maximale Logogröße:',
    admin_header_upload_button: 'Logo hochladen',
    admin_header_save_button: 'Header-Änderungen speichern',
    admin_header_saving: 'Speichert...',
    admin_header_saved: 'Header-Konfiguration gespeichert.',
    admin_header_save_error: 'Header konnte nicht gespeichert werden',
    admin_header_logo_updated: 'Logo aktualisiert',
    admin_header_upload_error: 'Logo-Upload fehlgeschlagen',
    admin_header_select_file: 'Datei auswählen',
    admin_header_links_title: 'Link-Verwaltung',
    admin_header_add_link: 'Link hinzufügen',
    admin_header_links_empty: 'Keine Links für diesen Header.',
    admin_header_link_label_placeholder: 'Link-Titel',
    admin_header_link_url_placeholder: 'URL (z.B. /search)',
    auth: {
      login: {
        info_banner: 'Willkommen bei Annoncia, Europas neuer und umfangreicher Kleinanzeigenplattform. Erstellen Sie kostenlos ein Konto.',
        title: 'Anmelden',
        subtitle: 'Melden Sie sich bei Ihrem Konto an.',
        portal_type: 'Anmeldeart',
        portal_account: 'Privat',
        portal_dealer: 'Gewerblich',
        email_placeholder: 'E-Mail-Adresse',
        password_placeholder: 'Passwort',
        remember_me: 'Angemeldet bleiben',
        forgot_password: 'Passwort vergessen',
        submit: 'Mit E-Mail anmelden',
        submit_loading: 'Lädt...',
        no_account: 'Noch kein Konto?',
        create_account: 'Konto erstellen',
        or: 'ODER',
        google_soon: 'Mit Google anmelden (Bald)',
        apple_soon: 'Mit Apple anmelden (Bald)',
        qr_login: 'Per QR-Code über die mobile App anmelden',
        totp_label: '2FA-Code',
        totp_placeholder: '6-stelliger Bestätigungscode',
        totp_help: 'Code aus Ihrer Authenticator-App eingeben.',
        admin: {
          session_verified: 'Sitzung bestätigt',
          loading_panel: 'Admin-Panel wird geladen...',
        },
        errors: {
          invalid_credentials: 'E-Mail oder Passwort ist falsch',
          invalid_totp: 'Bestätigungscode ist falsch',
          totp_required: '2FA-Code erforderlich',
          totp_setup_incomplete: '2FA-Setup nicht abgeschlossen',
          account_deleted: 'Konto wurde gelöscht',
          account_suspended: 'Konto wurde gesperrt',
          rate_limited: 'Zu viele Versuche. Bitte versuchen Sie es in 15 Minuten erneut.',
          email_not_verified: 'Sie müssen Ihr Konto bestätigen.',
          unknown: 'Anmeldung fehlgeschlagen. Bitte erneut versuchen.',
          send_verification: 'Bestätigungscode senden',
          temp_locked: 'Aus Sicherheitsgründen vorübergehend blockiert.',
          account_locked_help: 'Ist Ihr Konto gesperrt?',
          portal_mismatch_admin: 'Dies ist ein Admin-Konto. Bitte Admin-Login verwenden.',
          portal_mismatch_account: 'Dieses Konto ist für private Anmeldung bestimmt.',
          portal_mismatch_dealer: 'Dieses Konto ist für gewerbliche Anmeldung bestimmt.',
        },
      },
      register: {
        title_dealer: 'Gewerbliche Registrierung',
        title_individual: 'Private Registrierung',
        subtitle: 'Erstellen Sie Ihr Konto, indem Sie Ihre Daten eingeben.',
        verify_banner: 'Der Bestätigungscode wurde gesendet. Bitte den 6-stelligen Code eingeben.',
        company_name: 'Firmenname',
        contact_name: 'Ansprechperson',
        full_name: 'Vor- und Nachname',
        country: 'Land',
        select_country: 'Land auswählen',
        countries_loading: 'Länder werden geladen...',
        tax_optional: 'Steuer / ID (optional)',
        submit: 'Konto erstellen',
        submit_loading: 'Speichert...',
        code_label: 'Bestätigungscode',
        attempts_left: 'Verbleibende Versuche: {{count}}',
        verify_submit: 'Bestätigen',
        verify_loading: 'Wird bestätigt...',
        resend_code: 'Code erneut senden',
        resend_code_with_timer: 'Code erneut senden ({{seconds}}s)',
        back_to_login: 'Zurück zur Anmeldung',
        already_have_account: 'Haben Sie bereits ein Konto?',
        login: 'Anmelden',
        company_name_placeholder: 'z.B. Annoncia Motors',
        contact_name_placeholder: 'z.B. Ayşe Yılmaz',
        full_name_placeholder: 'z.B. Ali Demir',
        email_placeholder: 'mail@beispiel.com',
        password_placeholder: 'Mindestens 8 Zeichen',
        tax_placeholder: 'Steuernummer',
        toast: {
          code_sent_title: 'Bestätigungscode gesendet',
          code_sent_desc: 'Bitte prüfen Sie Ihre E-Mails.',
          verify_success_title: 'Bestätigung abgeschlossen',
          verify_success_desc: 'Ihr Konto wurde bestätigt.',
          code_resent_title: 'Code erneut gesendet',
        },
        errors: {
          countries_failed: 'Länder konnten nicht geladen werden',
          country_list_fallback: 'Länderliste nicht verfügbar. Standardland wird verwendet.',
          company_contact_required: 'Firmenname und Ansprechperson sind erforderlich.',
          fullname_required: 'Vollständiger Name ist erforderlich.',
          email_required: 'E-Mail ist erforderlich.',
          password_min: 'Passwort muss mindestens 8 Zeichen haben.',
          country_required: 'Landauswahl ist erforderlich.',
          register_failed: 'Registrierung fehlgeschlagen',
          code_required: 'Bitte den 6-stelligen Code eingeben.',
          too_many_attempts: 'Zu viele Versuche. Bitte warten.',
          code_invalid: 'Code konnte nicht bestätigt werden.',
          resend_wait: 'Vor kurzem gesendet. Bitte warten.',
          code_send_failed: 'Code konnte nicht gesendet werden.',
        },
      },
      verify: {
        info_banner: 'Willkommen bei Annoncia. Bitte geben Sie den E-Mail-Bestätigungscode ein.',
        title: 'E-Mail-Bestätigung',
        subtitle: 'Bestätigen Sie Ihr Konto mit dem 6-stelligen Code.',
        code_label: 'Bestätigungscode',
        attempts_left: 'Verbleibende Versuche: {{count}}',
        submit: 'Bestätigen',
        submit_loading: 'Wird bestätigt...',
        resend_code: 'Code erneut senden',
        resend_code_with_timer: 'Code erneut senden ({{seconds}}s)',
        no_code: 'Keinen Code erhalten?',
        back_to_login: 'Zurück zur Anmeldung',
        help_title: 'Hilfe',
        help_spam: 'Prüfen Sie den Spam- oder Junk-Ordner.',
        help_resend: 'Nutzen Sie nach 90 Sekunden die erneute Zusendung.',
        help_support_prefix: 'Falls das Problem weiter besteht,',
        help_support_link: 'kontaktieren Sie den Support',
        email_placeholder: 'mail@beispiel.com',
        toast: {
          success_title: 'Bestätigung abgeschlossen',
          success_desc: 'Ihr Konto wurde freigeschaltet.',
          resent_title: 'Code erneut gesendet',
          sent_desc: 'Bitte prüfen Sie Ihre E-Mails.',
        },
        errors: {
          email_required: 'E-Mail ist erforderlich.',
          code_required: 'Bitte den 6-stelligen Code eingeben.',
          too_many_attempts: 'Zu viele Versuche. Bitte später erneut versuchen.',
          code_invalid: 'Code konnte nicht bestätigt werden.',
          resend_wait: 'Vor kurzem gesendet. Bitte warten.',
          code_send_failed: 'Code konnte nicht gesendet werden.',
        },
      },
    },
    dealer: {
      layout: {
        user_fallback: 'Firmenbenutzer',
        brand_fallback: 'S Ofisim',
        search_placeholder: 'Anzeige, Kunde oder Bericht suchen',
        create_listing: 'Anzeige erstellen',
        quick_action_shortcut: 'Shortcut',
        quick_action_messages: 'Nachrichten',
        profile_settings: 'Profil / Einstellungen',
        logout: 'Abmelden',
        store_filter: 'Filialfilter',
        all_stores: 'Alle',
        finish_edit: 'Bearbeitung beenden',
        edit_page: 'Seite bearbeiten',
        announcements: 'Ankündigungen',
        quick_menu_title: 'Persönliches Schnellmenü',
        quick_menu_edit: 'Bearbeiten',
        quick_menu_close: 'Schließen',
        quick_menu_recent: 'Zuletzt verwendet',
        quick_menu_favorites: 'Meine Favoriten',
        quick_menu_empty: 'Keine Elemente in diesem Tab. Über Bearbeiten können Favoriten hinzugefügt werden.',
        quick_menu_search_placeholder: 'Menü suchen...',
        menu_fallback_title: 'Menü',
        menu_subtitle: 'Unterpunkte des in Zeile 2 gewählten Menüs',
        menu_loading: 'Menü wird geladen…',
      },
      settings: {
        title: 'Mein Konto',
        subtitle: 'Kontoinformationen, Sicherheit, Zahlung und Benachrichtigungen.',
        refresh: 'Aktualisieren',
        section_nav_title: 'Kontobereiche',
        loading: 'Lädt...',
        save: 'Speichern',
        save_success_profile: 'Profilinformationen gespeichert.',
        save_success_preferences: 'Benachrichtigungseinstellungen gespeichert.',
        security_2fa_active: 'Aktiv',
        security_2fa_inactive: 'Inaktiv',
        security_last_login: 'Letzte Anmeldung',
        sections: {
          profile: 'Kontoinformationen',
          address: 'Filialinformationen',
          security: 'Sicherheit',
          store_users: 'Benutzerliste / Hinzufügen',
          packages_services: 'Pakete und Services',
          saved_cards: 'Gespeicherte Karten',
          invoices: 'Rechnungen',
          account_movements: 'Kontobewegungen',
          notifications: 'Benachrichtigungseinstellungen',
          blocked: 'Blockierte Konten',
        },
        security: {
          save_button: 'Sicherheitsinformationen speichern',
        },
      },
    },
  },
  fr: {
    dashboard: 'Tableau de bord',
    users: 'Utilisateurs',
    countries: 'Pays',
    feature_flags: 'Flags de fonctionnalités',
    audit_logs: 'Journaux d\'audit',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    login: 'Connexion',
    email: 'E-mail',
    password: 'Mot de passe',
    submit: 'Soumettre',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    create: 'Créer',
    search: 'Rechercher',
    filter: 'Filtrer',
    all: 'Tous',
    active: 'Actif',
    inactive: 'Inactif',
    enabled: 'Activé',
    disabled: 'Désactivé',
    actions: 'Actions',
    status: 'Statut',
    name: 'Nom',
    role: 'Rôle',
    created_at: 'Créé le',
    updated_at: 'Mis à jour',
    total_users: 'Total utilisateurs',
    active_users: 'Utilisateurs actifs',
    enabled_countries: 'Pays actifs',
    enabled_features: 'Fonctionnalités actives',
    recent_activity: 'Activité récente',
    super_admin: 'Super Admin',
    country_admin: 'Admin Pays',
    moderator: 'Modérateur',
    support: 'Support',
    finance: 'Finance',
    module: 'Module',
    feature: 'Fonctionnalité',
    toggle: 'Basculer',
    welcome_back: 'Bon retour',
    login_subtitle: 'Connectez-vous pour accéder au panneau d\'administration',
    login_success: 'Connexion réussie',
    login_error: 'Échec de la connexion',
    save_success: 'Enregistré',
    delete_success: 'Supprimé',
    // Portals
    portal_consumer: 'Portail personnel',
    portal_dealer: 'Portail professionnel',
    nav_section: 'Menu',
    nav_listings: 'Gestion des annonces',
    nav_favorites: 'Favoris',
    nav_messages: 'Messages & notifications',
    nav_services: 'Services',
    nav_account: 'Compte',
    nav_dashboard: 'Vue d\'ensemble',
    nav_my_listings: 'Mes annonces',
    nav_create_listing: 'Nouvelle annonce',
    nav_support: 'Demandes de support',
    nav_profile: 'Profil',
    nav_privacy_center: 'Centre de confidentialité',
    nav_favorite_listings: 'Annonces favorites',
    nav_invoices: 'Factures',
    nav_company: 'Société',
    nav_company_profile: 'Profil société',
    nav_dealer_dashboard: 'Tableau pro',
    nav_overview: 'Vue d\'ensemble',
    nav_active_listings: 'Annonces actives',
    nav_draft_listings: 'Brouillons',
    nav_archived_listings: 'Archive',
    nav_favorite_searches: 'Recherches favorites',
    nav_inbox: 'Boîte de réception',
    nav_notifications: 'Notifications',
    nav_support_center: 'Centre support',
    nav_security: 'Sécurité',
    nav_data_export: 'Export des données',
    nav_account_delete: 'Supprimer le compte',
    nav_permissions: 'Consentements',
    nav_plan_quota: 'Plan et quota',
    nav_billing_overview: 'Aperçu facturation',
    nav_invoice_history: 'Historique des factures',
    nav_payment_methods: 'Moyens de paiement',
    nav_company_team: 'Équipe & rôles',
    nav_company_branches: 'Agences',
    portal_demo_title: 'Aperçu du portail',
    portal_demo_subtitle: 'Structure conforme aux standards EU et GDPR.',
    portal_demo_consumer: 'Particulier',
    portal_demo_dealer: 'Professionnel',
    portal_demo_consumer_title: 'Espace personnel',
    portal_demo_dealer_title: 'Espace professionnel',
    portal_demo_gdpr_title: 'Note GDPR',
    portal_demo_gdpr_text: 'Accès, export et suppression des données sont gérés dans le centre de confidentialité.',
    card_active_listings: 'Annonces actives',
    card_favorites: 'Favoris',
    card_messages: 'Messages',
    card_quota: 'Quota utilisé',
    card_balance: 'Montant facturé',
    header_user_fallback: 'Utilisateur',
    header_search_placeholder: 'Rechercher',
    header_suggestions_loading: 'Suggestions en chargement…',
    header_create_listing: 'Publier une annonce',
    header_login: 'Connexion',
    header_register: 'S’inscrire',
    header_messages: 'Messages',
    header_notifications: 'Notifications',
    header_favorites: 'Favoris',
    header_profile: 'Profil',
    header_settings: 'Paramètres',
    header_logout: 'Déconnexion',
    admin_header_title: 'Gestion du header',
    admin_header_subtitle: 'Gérez les headers invité, connecté et corporate.',
    admin_header_upload_hint: 'Taille maximale du logo :',
    admin_header_upload_button: 'Téléverser le logo',
    admin_header_save_button: 'Enregistrer les modifications',
    admin_header_saving: 'Enregistrement...',
    admin_header_saved: 'Configuration du header enregistrée.',
    admin_header_save_error: 'Échec de l’enregistrement du header',
    admin_header_logo_updated: 'Logo mis à jour',
    admin_header_upload_error: 'Échec du téléversement du logo',
    admin_header_select_file: 'Sélectionnez un fichier',
    admin_header_links_title: 'Gestion des liens',
    admin_header_add_link: 'Ajouter un lien',
    admin_header_links_empty: 'Aucun lien pour ce header.',
    admin_header_link_label_placeholder: 'Libellé du lien',
    admin_header_link_url_placeholder: 'URL (ex: /search)',
    auth: {
      login: {
        info_banner: 'Bienvenue sur Annoncia, la plus nouvelle et vaste plateforme d’annonces en Europe. Créez un compte gratuitement.',
        title: 'Connexion',
        subtitle: 'Connectez-vous à votre compte.',
        portal_type: 'Type de connexion',
        portal_account: 'Particulier',
        portal_dealer: 'Professionnel',
        email_placeholder: 'Adresse e-mail',
        password_placeholder: 'Mot de passe',
        remember_me: 'Rester connecté',
        forgot_password: 'Mot de passe oublié',
        submit: 'Se connecter par e-mail',
        submit_loading: 'Chargement...',
        no_account: 'Vous n’avez pas de compte ?',
        create_account: 'Créer un compte',
        or: 'OU',
        google_soon: 'Se connecter avec Google (Bientôt)',
        apple_soon: 'Se connecter avec Apple (Bientôt)',
        qr_login: 'Se connecter via QR code depuis l’application mobile',
        totp_label: 'Code 2FA',
        totp_placeholder: 'Code de vérification à 6 chiffres',
        totp_help: 'Saisissez le code de votre application Authenticator.',
        admin: {
          session_verified: 'Session vérifiée',
          loading_panel: 'Chargement du panneau admin...',
        },
        errors: {
          invalid_credentials: 'E-mail ou mot de passe incorrect',
          invalid_totp: 'Code de vérification incorrect',
          totp_required: 'Le code 2FA est requis',
          totp_setup_incomplete: 'Configuration 2FA incomplète',
          account_deleted: 'Compte supprimé',
          account_suspended: 'Compte suspendu',
          rate_limited: 'Trop de tentatives. Réessayez dans 15 minutes.',
          email_not_verified: 'Vous devez vérifier votre compte.',
          unknown: 'Échec de connexion. Veuillez réessayer.',
          send_verification: 'Envoyer le code de vérification',
          temp_locked: 'Bloqué temporairement pour des raisons de sécurité.',
          account_locked_help: 'Compte verrouillé ?',
          portal_mismatch_admin: 'Ce compte est un compte admin. Utilisez la connexion admin.',
          portal_mismatch_account: 'Ce compte est destiné à la connexion particulier.',
          portal_mismatch_dealer: 'Ce compte est destiné à la connexion professionnel.',
        },
      },
      register: {
        title_dealer: 'Inscription professionnelle',
        title_individual: 'Inscription individuelle',
        subtitle: 'Créez votre compte en renseignant vos informations.',
        verify_banner: 'Le code de vérification a été envoyé. Saisissez le code à 6 chiffres.',
        company_name: 'Nom de l’entreprise',
        contact_name: 'Personne autorisée',
        full_name: 'Nom complet',
        country: 'Pays',
        select_country: 'Choisissez un pays',
        countries_loading: 'Chargement des pays...',
        tax_optional: 'Taxe / ID (optionnel)',
        submit: 'Créer un compte',
        submit_loading: 'Enregistrement...',
        code_label: 'Code de vérification',
        attempts_left: 'Tentatives restantes : {{count}}',
        verify_submit: 'Vérifier',
        verify_loading: 'Vérification...',
        resend_code: 'Renvoyer le code',
        resend_code_with_timer: 'Renvoyer le code ({{seconds}}s)',
        back_to_login: 'Retour à la connexion',
        already_have_account: 'Vous avez déjà un compte ?',
        login: 'Connexion',
        company_name_placeholder: 'Ex: Annoncia Motors',
        contact_name_placeholder: 'Ex: Ayşe Yılmaz',
        full_name_placeholder: 'Ex: Ali Demir',
        email_placeholder: 'mail@exemple.com',
        password_placeholder: 'Au moins 8 caractères',
        tax_placeholder: 'Numéro fiscal',
        toast: {
          code_sent_title: 'Code de vérification envoyé',
          code_sent_desc: 'Veuillez vérifier votre e-mail.',
          verify_success_title: 'Vérification terminée',
          verify_success_desc: 'Votre compte a été vérifié.',
          code_resent_title: 'Code renvoyé',
        },
        errors: {
          countries_failed: 'Impossible de charger les pays',
          country_list_fallback: 'Liste des pays indisponible. Pays par défaut utilisé.',
          company_contact_required: 'Nom de société et personne autorisée requis.',
          fullname_required: 'Le nom complet est requis.',
          email_required: 'E-mail requis.',
          password_min: 'Le mot de passe doit contenir au moins 8 caractères.',
          country_required: 'La sélection du pays est requise.',
          register_failed: 'Échec de l’inscription',
          code_required: 'Saisissez le code à 6 chiffres.',
          too_many_attempts: 'Trop de tentatives. Veuillez patienter.',
          code_invalid: 'Le code n’a pas pu être vérifié.',
          resend_wait: 'Code envoyé récemment. Veuillez patienter.',
          code_send_failed: 'Impossible d’envoyer le code.',
        },
      },
      verify: {
        info_banner: 'Bienvenue sur Annoncia. Veuillez saisir votre code de vérification e-mail.',
        title: 'Vérification e-mail',
        subtitle: 'Validez votre compte avec le code à 6 chiffres.',
        code_label: 'Code de vérification',
        attempts_left: 'Tentatives restantes : {{count}}',
        submit: 'Vérifier',
        submit_loading: 'Vérification...',
        resend_code: 'Renvoyer le code',
        resend_code_with_timer: 'Renvoyer le code ({{seconds}}s)',
        no_code: 'Vous n’avez pas reçu le code ?',
        back_to_login: 'Retour à la connexion',
        help_title: 'Aide',
        help_spam: 'Vérifiez votre dossier spam ou indésirable.',
        help_resend: 'Utilisez le renvoi après 90 secondes.',
        help_support_prefix: 'Si le problème persiste,',
        help_support_link: 'contactez le support',
        email_placeholder: 'mail@exemple.com',
        toast: {
          success_title: 'Vérification terminée',
          success_desc: 'Votre compte a été approuvé.',
          resent_title: 'Code renvoyé',
          sent_desc: 'Veuillez vérifier votre e-mail.',
        },
        errors: {
          email_required: 'E-mail requis.',
          code_required: 'Saisissez le code à 6 chiffres.',
          too_many_attempts: 'Trop de tentatives. Réessayez plus tard.',
          code_invalid: 'Le code n’a pas pu être vérifié.',
          resend_wait: 'Code envoyé récemment. Veuillez patienter.',
          code_send_failed: 'Impossible d’envoyer le code.',
        },
      },
    },
    dealer: {
      layout: {
        user_fallback: 'Utilisateur professionnel',
        brand_fallback: 'S Ofisim',
        search_placeholder: 'Rechercher une annonce, un client ou un rapport',
        create_listing: 'Publier une annonce',
        quick_action_shortcut: 'Raccourci',
        quick_action_messages: 'Messages',
        profile_settings: 'Profil / Paramètres',
        logout: 'Déconnexion',
        store_filter: 'Filtre magasin',
        all_stores: 'Tous',
        finish_edit: 'Terminer la modification',
        edit_page: 'Modifier la page',
        announcements: 'Annonces',
        quick_menu_title: 'Menu rapide personnel',
        quick_menu_edit: 'Modifier',
        quick_menu_close: 'Fermer',
        quick_menu_recent: 'Récents',
        quick_menu_favorites: 'Mes favoris',
        quick_menu_empty: 'Aucun élément dans cet onglet. Ajoutez des favoris avec Modifier.',
        quick_menu_search_placeholder: 'Rechercher dans le menu...',
        menu_fallback_title: 'Menu',
        menu_subtitle: 'Sous-rubriques du menu sélectionné à la 2e ligne',
        menu_loading: 'Chargement du menu…',
      },
      settings: {
        title: 'Mon compte',
        subtitle: 'Informations du compte, sécurité, paiements et notifications.',
        refresh: 'Actualiser',
        section_nav_title: 'Sections du compte',
        loading: 'Chargement...',
        save: 'Enregistrer',
        save_success_profile: 'Informations du profil enregistrées.',
        save_success_preferences: 'Préférences de notification enregistrées.',
        security_2fa_active: 'Actif',
        security_2fa_inactive: 'Inactif',
        security_last_login: 'Dernière connexion',
        sections: {
          profile: 'Informations du compte',
          address: 'Informations magasin',
          security: 'Sécurité',
          store_users: 'Liste utilisateurs / Ajouter',
          packages_services: 'Forfaits et services',
          saved_cards: 'Cartes enregistrées',
          invoices: 'Factures',
          account_movements: 'Mouvements du compte',
          notifications: 'Préférences de notification',
          blocked: 'Comptes bloqués',
        },
        security: {
          save_button: 'Enregistrer les informations de sécurité',
        },
      },
    },
  }
};

if (!i18n.isInitialized) {
  i18n
    .use(initReactI18next)
    .init({
      resources: {
        tr: { translation: translations.tr },
        de: { translation: translations.de },
        fr: { translation: translations.fr },
      },
      lng: localStorage.getItem('language') || 'tr',
      fallbackLng: 'tr',
      interpolation: {
        escapeValue: false,
      },
    })
    .catch(() => undefined);
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || i18n.resolvedLanguage || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    i18n.changeLanguage(language).catch(() => undefined);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    const handleLanguageChange = (nextLanguage) => {
      setLanguage(nextLanguage || 'tr');
    };
    i18n.on('languageChanged', handleLanguageChange);
    return () => {
      i18n.off('languageChanged', handleLanguageChange);
    };
  }, []);

  const t = (key, fallbackOrOptions = undefined, maybeOptions = undefined) => {
    if (typeof fallbackOrOptions === 'string') {
      return i18n.t(key, { defaultValue: fallbackOrOptions, ...(maybeOptions || {}) });
    }
    if (fallbackOrOptions && typeof fallbackOrOptions === 'object') {
      return i18n.t(key, fallbackOrOptions);
    }
    return i18n.t(key, { defaultValue: key });
  };

  const getTranslated = (obj) => {
    if (!obj) return '';
    return obj[language] || obj.tr || obj.de || obj.fr || Object.values(obj)[0] || '';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getTranslated }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
