import { createContext, useContext, useState, useEffect } from 'react';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const translations = {
  tr: {
    // Common
    dashboard: 'Kontrol Paneli',
    users: 'Kullanıcılar',
    countries: 'Ülkeler',
    feature_flags: 'Özellik Bayrakları',
    audit_logs: 'Denetim Kayıtları',
    settings: 'Ayarlar',
    logout: 'Çıkış',
    login: 'Giriş',
    email: 'E-posta',
    password: 'Şifre',
    submit: 'Gönder',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    create: 'Oluştur',
    search: 'Ara',
    filter: 'Filtre',
    all: 'Tümü',
    active: 'Aktif',
    inactive: 'Pasif',
    enabled: 'Etkin',
    disabled: 'Devre Dışı',
    actions: 'İşlemler',
    status: 'Durum',
    name: 'Ad',
    role: 'Rol',
    created_at: 'Oluşturulma',
    updated_at: 'Güncelleme',
    // Dashboard
    total_users: 'Toplam Kullanıcı',
    active_users: 'Aktif Kullanıcı',
    enabled_countries: 'Aktif Ülke',
    enabled_features: 'Aktif Özellik',
    recent_activity: 'Son Aktivite',
    // Roles
    super_admin: 'Süper Admin',
    country_admin: 'Ülke Admin',
    moderator: 'Moderatör',
    support: 'Destek',
    finance: 'Finans',
    // Feature Flags
    module: 'Modül',
    feature: 'Özellik',
    enabled_countries: 'Aktif Ülkeler',
    toggle: 'Aç/Kapa',
    // Auth
    welcome_back: 'Tekrar Hoşgeldiniz',
    login_subtitle: 'Admin paneline erişmek için giriş yapın',
    // Messages
    login_success: 'Giriş başarılı',
    login_error: 'Giriş başarısız',
    save_success: 'Kaydedildi',
    delete_success: 'Silindi',
    // Portals
    portal_consumer: 'Bireysel Portal',
    portal_dealer: 'Ticari Portal',
    nav_section: 'Menü',
    nav_listings: 'İlan Yönetimi',
    nav_favorites: 'Favoriler',
    nav_messages: 'Mesajlar & Bildirimler',
    nav_services: 'Servisler',
    nav_account: 'Hesabım',
    nav_dashboard: 'Özet',
    nav_my_listings: 'İlanlarım',
    nav_create_listing: 'Yeni İlan',
    nav_support: 'Destek Talepleri',
    nav_profile: 'Profil',
    nav_privacy_center: 'Gizlilik Merkezi',
    nav_favorite_listings: 'Favori İlanlar',
    nav_invoices: 'Faturalar',
    nav_company: 'Şirket',
    nav_dealer_dashboard: 'Panel',
    nav_overview: 'Özet',
    nav_active_listings: 'Yayındaki İlanlar',
    nav_draft_listings: 'Taslaklar',
    nav_archived_listings: 'Arşiv',
    nav_favorite_searches: 'Favori Aramalar',
    nav_inbox: 'Gelen Kutusu',
    nav_notifications: 'Bildirimler',
    nav_support_center: 'Destek Merkezi',
    nav_security: 'Güvenlik',
    nav_data_export: 'Veri Dışa Aktarım',
    nav_account_delete: 'Hesap Silme',
    nav_permissions: 'İzinler',
    nav_plan_quota: 'Plan ve Kota',
    nav_billing_overview: 'Faturalandırma Özeti',
    nav_invoice_history: 'Fatura Geçmişi',
    nav_payment_methods: 'Ödeme Yöntemleri',
    nav_company_team: 'Ekip ve Yetkiler',
    nav_company_branches: 'Şubeler',
    portal_demo_title: 'Portal Önizleme',
    portal_demo_subtitle: 'Avrupa standartlarında menü yapısı ve GDPR odakları.',
    portal_demo_consumer: 'Bireysel',
    portal_demo_dealer: 'Ticari',
    portal_demo_consumer_title: 'Bireysel Kontrol Alanı',
    portal_demo_dealer_title: 'Ticari Kontrol Alanı',
    portal_demo_gdpr_title: 'GDPR Güvenlik Notu',
    portal_demo_gdpr_text: 'Veri erişimi, dışa aktarma ve hesap silme adımları gizlilik merkezinden yönetilir.',
    card_active_listings: 'Yayındaki İlan',
    card_favorites: 'Favori',
    card_messages: 'Mesaj',
    card_quota: 'Kota Kullanımı',
    card_balance: 'Fatura Toplamı',
    header_user_fallback: 'Kullanıcı',
    header_search_placeholder: 'Arama yap',
    header_suggestions_loading: 'Öneriler yükleniyor…',
    header_create_listing: 'İlan Ver',
    header_login: 'Giriş Yap',
    header_register: 'Üye Ol',
    header_messages: 'Mesajlar',
    header_notifications: 'Bildirimler',
    header_favorites: 'Favoriler',
    header_profile: 'Profil',
    header_settings: 'Ayarlar',
    header_logout: 'Çıkış',
    admin_header_title: 'Header Yönetimi',
    admin_header_subtitle: 'Guest, authenticated ve kurumsal header içeriğini yönetin.',
    admin_header_upload_hint: 'Maksimum logo boyutu:',
    admin_header_upload_button: 'Logo Yükle',
    admin_header_save_button: 'Header Değişikliklerini Kaydet',
    admin_header_saving: 'Kaydediliyor...',
    admin_header_saved: 'Header yapılandırması kaydedildi.',
    admin_header_save_error: 'Header kaydedilemedi',
    admin_header_logo_updated: 'Logo güncellendi',
    admin_header_upload_error: 'Logo yükleme başarısız',
    admin_header_select_file: 'Dosya seçin',
    admin_header_links_title: 'Link Yönetimi',
    admin_header_add_link: 'Link Ekle',
    admin_header_links_empty: 'Bu header için link bulunmuyor.',
    admin_header_link_label_placeholder: 'Link etiketi',
    admin_header_link_url_placeholder: 'URL (örn: /search)',
  },
  de: {
    dashboard: 'Dashboard',
    users: 'Benutzer',
    countries: 'Länder',
    feature_flags: 'Feature Flags',
    audit_logs: 'Audit-Protokolle',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    login: 'Anmelden',
    email: 'E-Mail',
    password: 'Passwort',
    submit: 'Absenden',
    cancel: 'Abbrechen',
    save: 'Speichern',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    create: 'Erstellen',
    search: 'Suchen',
    filter: 'Filter',
    all: 'Alle',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    enabled: 'Aktiviert',
    disabled: 'Deaktiviert',
    actions: 'Aktionen',
    status: 'Status',
    name: 'Name',
    role: 'Rolle',
    created_at: 'Erstellt',
    updated_at: 'Aktualisiert',
    total_users: 'Gesamtbenutzer',
    active_users: 'Aktive Benutzer',
    enabled_countries: 'Aktive Länder',
    enabled_features: 'Aktive Features',
    recent_activity: 'Letzte Aktivität',
    super_admin: 'Super Admin',
    country_admin: 'Länder Admin',
    moderator: 'Moderator',
    support: 'Support',
    finance: 'Finanzen',
    module: 'Modul',
    feature: 'Feature',
    toggle: 'Umschalten',
    welcome_back: 'Willkommen zurück',
    login_subtitle: 'Melden Sie sich an, um auf das Admin-Panel zuzugreifen',
    login_success: 'Erfolgreich angemeldet',
    login_error: 'Anmeldung fehlgeschlagen',
    save_success: 'Gespeichert',
    delete_success: 'Gelöscht',
    // Portals
    portal_consumer: 'Privates Portal',
    portal_dealer: 'Gewerbliches Portal',
    nav_section: 'Menü',
    nav_listings: 'Anzeigenverwaltung',
    nav_favorites: 'Favoriten',
    nav_messages: 'Nachrichten & Hinweise',
    nav_services: 'Services',
    nav_account: 'Konto',
    nav_dashboard: 'Übersicht',
    nav_my_listings: 'Meine Anzeigen',
    nav_create_listing: 'Neue Anzeige',
    nav_support: 'Support-Tickets',
    nav_profile: 'Profil',
    nav_privacy_center: 'Datenschutz-Zentrum',
    nav_favorite_listings: 'Favorisierte Anzeigen',
    nav_invoices: 'Rechnungen',
    nav_company: 'Unternehmen',
    nav_company_profile: 'Unternehmensprofil',
    nav_dealer_dashboard: 'Portal-Übersicht',
    nav_overview: 'Übersicht',
    nav_active_listings: 'Aktive Anzeigen',
    nav_draft_listings: 'Entwürfe',
    nav_archived_listings: 'Archiv',
    nav_favorite_searches: 'Favorisierte Suchen',
    nav_inbox: 'Posteingang',
    nav_notifications: 'Benachrichtigungen',
    nav_support_center: 'Support-Zentrum',
    nav_security: 'Sicherheit',
    nav_data_export: 'Datenexport',
    nav_account_delete: 'Konto löschen',
    nav_permissions: 'Einwilligungen',
    nav_plan_quota: 'Plan & Kontingent',
    nav_billing_overview: 'Abrechnungsübersicht',
    nav_invoice_history: 'Rechnungsverlauf',
    nav_payment_methods: 'Zahlungsmethoden',
    nav_company_team: 'Team & Rollen',
    nav_company_branches: 'Filialen',
    portal_demo_title: 'Portal-Vorschau',
    portal_demo_subtitle: 'Menüstruktur nach EU-Standards mit GDPR-Fokus.',
    portal_demo_consumer: 'Privat',
    portal_demo_dealer: 'Gewerblich',
    portal_demo_consumer_title: 'Privater Kontrollbereich',
    portal_demo_dealer_title: 'Gewerblicher Kontrollbereich',
    portal_demo_gdpr_title: 'GDPR Sicherheitshinweis',
    portal_demo_gdpr_text: 'Datenzugriff, Export und Löschung werden im Datenschutz-Zentrum verwaltet.',
    card_active_listings: 'Aktive Anzeigen',
    card_favorites: 'Favoriten',
    card_messages: 'Nachrichten',
    card_quota: 'Kontingent',
    card_balance: 'Rechnungsbetrag',
    header_user_fallback: 'Benutzer',
    header_search_placeholder: 'Suche',
    header_suggestions_loading: 'Vorschläge werden geladen…',
    header_create_listing: 'Anzeige aufgeben',
    header_login: 'Anmelden',
    header_register: 'Registrieren',
    header_messages: 'Nachrichten',
    header_notifications: 'Benachrichtigungen',
    header_favorites: 'Favoriten',
    header_profile: 'Profil',
    header_settings: 'Einstellungen',
    header_logout: 'Abmelden',
    admin_header_title: 'Header-Verwaltung',
    admin_header_subtitle: 'Verwalten Sie Guest-, Auth- und Corporate-Header.',
    admin_header_upload_hint: 'Maximale Logogröße:',
    admin_header_upload_button: 'Logo hochladen',
    admin_header_save_button: 'Header-Änderungen speichern',
    admin_header_saving: 'Speichert...',
    admin_header_saved: 'Header-Konfiguration gespeichert.',
    admin_header_save_error: 'Header konnte nicht gespeichert werden',
    admin_header_logo_updated: 'Logo aktualisiert',
    admin_header_upload_error: 'Logo-Upload fehlgeschlagen',
    admin_header_select_file: 'Datei auswählen',
    admin_header_links_title: 'Link-Verwaltung',
    admin_header_add_link: 'Link hinzufügen',
    admin_header_links_empty: 'Keine Links für diesen Header.',
    admin_header_link_label_placeholder: 'Link-Titel',
    admin_header_link_url_placeholder: 'URL (z.B. /search)',
  },
  fr: {
    dashboard: 'Tableau de bord',
    users: 'Utilisateurs',
    countries: 'Pays',
    feature_flags: 'Flags de fonctionnalités',
    audit_logs: 'Journaux d\'audit',
    settings: 'Paramètres',
    logout: 'Déconnexion',
    login: 'Connexion',
    email: 'E-mail',
    password: 'Mot de passe',
    submit: 'Soumettre',
    cancel: 'Annuler',
    save: 'Enregistrer',
    delete: 'Supprimer',
    edit: 'Modifier',
    create: 'Créer',
    search: 'Rechercher',
    filter: 'Filtrer',
    all: 'Tous',
    active: 'Actif',
    inactive: 'Inactif',
    enabled: 'Activé',
    disabled: 'Désactivé',
    actions: 'Actions',
    status: 'Statut',
    name: 'Nom',
    role: 'Rôle',
    created_at: 'Créé le',
    updated_at: 'Mis à jour',
    total_users: 'Total utilisateurs',
    active_users: 'Utilisateurs actifs',
    enabled_countries: 'Pays actifs',
    enabled_features: 'Fonctionnalités actives',
    recent_activity: 'Activité récente',
    super_admin: 'Super Admin',
    country_admin: 'Admin Pays',
    moderator: 'Modérateur',
    support: 'Support',
    finance: 'Finance',
    module: 'Module',
    feature: 'Fonctionnalité',
    toggle: 'Basculer',
    welcome_back: 'Bon retour',
    login_subtitle: 'Connectez-vous pour accéder au panneau d\'administration',
    login_success: 'Connexion réussie',
    login_error: 'Échec de la connexion',
    save_success: 'Enregistré',
    delete_success: 'Supprimé',
    // Portals
    portal_consumer: 'Portail personnel',
    portal_dealer: 'Portail professionnel',
    nav_section: 'Menu',
    nav_listings: 'Gestion des annonces',
    nav_favorites: 'Favoris',
    nav_messages: 'Messages & notifications',
    nav_services: 'Services',
    nav_account: 'Compte',
    nav_dashboard: 'Vue d\'ensemble',
    nav_my_listings: 'Mes annonces',
    nav_create_listing: 'Nouvelle annonce',
    nav_support: 'Demandes de support',
    nav_profile: 'Profil',
    nav_privacy_center: 'Centre de confidentialité',
    nav_favorite_listings: 'Annonces favorites',
    nav_invoices: 'Factures',
    nav_company: 'Société',
    nav_company_profile: 'Profil société',
    nav_dealer_dashboard: 'Tableau pro',
    nav_overview: 'Vue d\'ensemble',
    nav_active_listings: 'Annonces actives',
    nav_draft_listings: 'Brouillons',
    nav_archived_listings: 'Archive',
    nav_favorite_searches: 'Recherches favorites',
    nav_inbox: 'Boîte de réception',
    nav_notifications: 'Notifications',
    nav_support_center: 'Centre support',
    nav_security: 'Sécurité',
    nav_data_export: 'Export des données',
    nav_account_delete: 'Supprimer le compte',
    nav_permissions: 'Consentements',
    nav_plan_quota: 'Plan et quota',
    nav_billing_overview: 'Aperçu facturation',
    nav_invoice_history: 'Historique des factures',
    nav_payment_methods: 'Moyens de paiement',
    nav_company_team: 'Équipe & rôles',
    nav_company_branches: 'Agences',
    portal_demo_title: 'Aperçu du portail',
    portal_demo_subtitle: 'Structure conforme aux standards EU et GDPR.',
    portal_demo_consumer: 'Particulier',
    portal_demo_dealer: 'Professionnel',
    portal_demo_consumer_title: 'Espace personnel',
    portal_demo_dealer_title: 'Espace professionnel',
    portal_demo_gdpr_title: 'Note GDPR',
    portal_demo_gdpr_text: 'Accès, export et suppression des données sont gérés dans le centre de confidentialité.',
    card_active_listings: 'Annonces actives',
    card_favorites: 'Favoris',
    card_messages: 'Messages',
    card_quota: 'Quota utilisé',
    card_balance: 'Montant facturé',
    header_user_fallback: 'Utilisateur',
    header_search_placeholder: 'Rechercher',
    header_suggestions_loading: 'Suggestions en chargement…',
    header_create_listing: 'Publier une annonce',
    header_login: 'Connexion',
    header_register: 'S’inscrire',
    header_messages: 'Messages',
    header_notifications: 'Notifications',
    header_favorites: 'Favoris',
    header_profile: 'Profil',
    header_settings: 'Paramètres',
    header_logout: 'Déconnexion',
    admin_header_title: 'Gestion du header',
    admin_header_subtitle: 'Gérez les headers invité, connecté et corporate.',
    admin_header_upload_hint: 'Taille maximale du logo :',
    admin_header_upload_button: 'Téléverser le logo',
    admin_header_save_button: 'Enregistrer les modifications',
    admin_header_saving: 'Enregistrement...',
    admin_header_saved: 'Configuration du header enregistrée.',
    admin_header_save_error: 'Échec de l’enregistrement du header',
    admin_header_logo_updated: 'Logo mis à jour',
    admin_header_upload_error: 'Échec du téléversement du logo',
    admin_header_select_file: 'Sélectionnez un fichier',
    admin_header_links_title: 'Gestion des liens',
    admin_header_add_link: 'Ajouter un lien',
    admin_header_links_empty: 'Aucun lien pour ce header.',
    admin_header_link_label_placeholder: 'Libellé du lien',
    admin_header_link_url_placeholder: 'URL (ex: /search)',
  }
};

if (!i18n.isInitialized) {
  i18n
    .use(initReactI18next)
    .init({
      resources: {
        tr: { translation: translations.tr },
        de: { translation: translations.de },
        fr: { translation: translations.fr },
      },
      lng: localStorage.getItem('language') || 'tr',
      fallbackLng: 'tr',
      interpolation: {
        escapeValue: false,
      },
    })
    .catch(() => undefined);
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || i18n.resolvedLanguage || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    i18n.changeLanguage(language).catch(() => undefined);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    const handleLanguageChange = (nextLanguage) => {
      setLanguage(nextLanguage || 'tr');
    };
    i18n.on('languageChanged', handleLanguageChange);
    return () => {
      i18n.off('languageChanged', handleLanguageChange);
    };
  }, []);

  const t = (key) => {
    return i18n.t(key, { defaultValue: key });
  };

  const getTranslated = (obj) => {
    if (!obj) return '';
    return obj[language] || obj.tr || obj.de || obj.fr || Object.values(obj)[0] || '';
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, getTranslated }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
