"""Add is_showcase to Listing

Revision ID: 00ab8d47b5d4
Revises: cb79ce7dca3e
Create Date: 2026-02-14 01:38:23.647312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ab8d47b5d4'
down_revision: Union[str, Sequence[str], None] = 'cb79ce7dca3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_showcase', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('listings', sa.Column('showcase_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_listings_is_showcase'), 'listings', ['is_showcase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_is_showcase'), table_name='listings')
    op.drop_column('listings', 'showcase_expires_at')
    op.drop_column('listings', 'is_showcase')
    # ### end Alembic commands ###
