"""Add dealer_profiles table

Revision ID: 08d0f89018fa
Revises: ed602102b938
Create Date: 2026-02-16 21:10:29.201718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d0f89018fa'
down_revision: Union[str, Sequence[str], None] = 'ed602102b938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_country', sa.String(length=5), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('impressum_text', sa.Text(), nullable=True),
    sa.Column('terms_text', sa.Text(), nullable=True),
    sa.Column('withdrawal_policy_text', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealer_profiles')
    # ### end Alembic commands ###
