"""Add user_features table

Revision ID: 096c77d33b83
Revises: 2e7187f29f52
Create Date: 2026-02-16 19:35:52.988535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '096c77d33b83'
down_revision: Union[str, Sequence[str], None] = '2e7187f29f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_features',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_affinity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('city_affinity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_sensitivity', sa.Float(), nullable=False),
    sa.Column('activity_score', sa.Float(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_index(op.f('idx_user_device_token'), table_name='user_devices')
    op.drop_index(op.f('idx_user_device_user'), table_name='user_devices')
    op.drop_table('user_devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_rooted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_devices_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_devices_pkey')),
    sa.UniqueConstraint('token', name=op.f('user_devices_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_device_user'), 'user_devices', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_device_token'), 'user_devices', ['token'], unique=False)
    op.drop_table('user_features')
    # ### end Alembic commands ###
