"""Add analytics models

Revision ID: 0e2a0698338b
Revises: 3529d99b7d36
Create Date: 2026-02-14 15:06:24.509757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2a0698338b'
down_revision: Union[str, Sequence[str], None] = '3529d99b7d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_views_dedup', 'listing_views', ['listing_id', 'ip_hash', 'created_at'], unique=False)
    op.create_index(op.f('ix_listing_views_listing_id'), 'listing_views', ['listing_id'], unique=False)
    op.add_column('listings', sa.Column('view_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'view_count')
    op.drop_index(op.f('ix_listing_views_listing_id'), table_name='listing_views')
    op.drop_index('ix_listing_views_dedup', table_name='listing_views')
    op.drop_table('listing_views')
    # ### end Alembic commands ###
