"""Add pricing engine models and update subscription

Revision ID: 0e44994b5f92
Revises: 3403c9ea9d1a
Create Date: 2026-02-12 15:30:17.436533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e44994b5f92'
down_revision: Union[str, Sequence[str], None] = '3403c9ea9d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_currency_map',
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('country')
    )
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('country_scope', sa.String(length=5), nullable=False),
    sa.Column('segment_scope', sa.String(length=20), nullable=False),
    sa.Column('apply_to', sa.String(length=50), nullable=False),
    sa.Column('stacking_allowed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value >= 0', name='check_discount_value_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=False)
    op.create_table('free_quota_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('quota_amount', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('quota_scope', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quota_amount >= 0', name='check_quota_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_free_quota_configs_active_unique', 'free_quota_configs', ['country', 'segment'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_free_quota_configs_country'), 'free_quota_configs', ['country'], unique=False)
    op.create_index(op.f('ix_free_quota_configs_is_active'), 'free_quota_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_free_quota_configs_segment'), 'free_quota_configs', ['segment'], unique=False)
    op.create_table('price_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('pricing_type', sa.String(length=50), nullable=False),
    sa.Column('unit_price_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('price_version', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('unit_price_net >= 0', name='check_price_positive'),
    sa.ForeignKeyConstraint(['country'], ['country_currency_map.country'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_configs_active_unique', 'price_configs', ['country', 'segment', 'pricing_type'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_price_configs_country'), 'price_configs', ['country'], unique=False)
    op.create_index(op.f('ix_price_configs_is_active'), 'price_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_price_configs_pricing_type'), 'price_configs', ['pricing_type'], unique=False)
    op.create_index(op.f('ix_price_configs_segment'), 'price_configs', ['segment'], unique=False)
    op.create_table('listing_consumption_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consumed_source', sa.String(length=50), nullable=False),
    sa.Column('price_config_id', sa.UUID(), nullable=True),
    sa.Column('invoice_item_id', sa.UUID(), nullable=True),
    sa.Column('charged_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['price_config_id'], ['price_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consumption_logs_composite', 'listing_consumption_logs', ['dealer_id', 'consumed_source', 'created_at'], unique=False)
    op.create_index(op.f('ix_listing_consumption_logs_dealer_id'), 'listing_consumption_logs', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_listing_consumption_logs_listing_id'), 'listing_consumption_logs', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_consumption_logs_user_id'), 'listing_consumption_logs', ['user_id'], unique=False)
    op.add_column('dealer_subscriptions', sa.Column('used_listing_quota', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dealer_subscriptions', sa.Column('used_premium_quota', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dealer_subscriptions', sa.Column('included_listing_quota', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('dealer_subscriptions', sa.Column('included_premium_quota', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('dealer_subscriptions', 'remaining_listing_quota')
    op.drop_column('dealer_subscriptions', 'remaining_premium_quota')
    op.add_column('invoice_items', sa.Column('price_source', sa.String(length=50), nullable=False, server_default='manual'))
    op.add_column('invoice_items', sa.Column('base_unit_price', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('invoice_items', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('invoice_items', sa.Column('applied_vat_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default='0'))
    op.add_column('invoice_items', sa.Column('currency', sa.String(length=5), nullable=False, server_default='EUR'))
    op.add_column('invoice_items', sa.Column('country', sa.String(length=5), nullable=False, server_default='DE'))

    op.add_column('invoice_items', sa.Column('price_config_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'price_config_version')
    op.drop_column('invoice_items', 'country')
    op.drop_column('invoice_items', 'currency')
    op.drop_column('invoice_items', 'applied_vat_rate')
    op.drop_column('invoice_items', 'discount_amount')
    op.drop_column('invoice_items', 'base_unit_price')
    op.drop_column('invoice_items', 'price_source')
    op.add_column('dealer_subscriptions', sa.Column('remaining_premium_quota', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dealer_subscriptions', sa.Column('remaining_listing_quota', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('dealer_subscriptions', 'included_premium_quota')
    op.drop_column('dealer_subscriptions', 'included_listing_quota')
    op.drop_column('dealer_subscriptions', 'used_premium_quota')
    op.drop_column('dealer_subscriptions', 'used_listing_quota')
    op.drop_index(op.f('ix_listing_consumption_logs_user_id'), table_name='listing_consumption_logs')
    op.drop_index(op.f('ix_listing_consumption_logs_listing_id'), table_name='listing_consumption_logs')
    op.drop_index(op.f('ix_listing_consumption_logs_dealer_id'), table_name='listing_consumption_logs')
    op.drop_index('ix_consumption_logs_composite', table_name='listing_consumption_logs')
    op.drop_table('listing_consumption_logs')
    op.drop_index(op.f('ix_price_configs_segment'), table_name='price_configs')
    op.drop_index(op.f('ix_price_configs_pricing_type'), table_name='price_configs')
    op.drop_index(op.f('ix_price_configs_is_active'), table_name='price_configs')
    op.drop_index(op.f('ix_price_configs_country'), table_name='price_configs')
    op.drop_index('ix_price_configs_active_unique', table_name='price_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_table('price_configs')
    op.drop_index(op.f('ix_free_quota_configs_segment'), table_name='free_quota_configs')
    op.drop_index(op.f('ix_free_quota_configs_is_active'), table_name='free_quota_configs')
    op.drop_index(op.f('ix_free_quota_configs_country'), table_name='free_quota_configs')
    op.drop_index('ix_free_quota_configs_active_unique', table_name='free_quota_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_table('free_quota_configs')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.drop_table('discounts')
    op.drop_table('country_currency_map')
    # ### end Alembic commands ###
