"""Add affiliate system

Revision ID: 0f8f8129feda
Revises: 44ec5e23b2dc
Create Date: 2026-02-16 16:23:51.651284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f8f8129feda'
down_revision: Union[str, Sequence[str], None] = '44ec5e23b2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('custom_slug', sa.String(length=50), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payout_details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliates_custom_slug'), 'affiliates', ['custom_slug'], unique=True)
    op.create_index(op.f('ix_affiliates_status'), 'affiliates', ['status'], unique=False)
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=True)
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_affiliate_id'), 'affiliate_clicks', ['affiliate_id'], unique=False)
    op.create_index('ix_affiliate_clicks_date', 'affiliate_clicks', ['affiliate_id', 'created_at'], unique=False)
    # op.drop_index(op.f('ix_listings_boosted_at'), table_name='listings')
    # op.drop_index(op.f('ix_listings_is_urgent'), table_name='listings')
    # op.drop_column('listings', 'is_urgent')
    # op.drop_column('listings', 'is_bold_title')
    # op.drop_column('listings', 'boosted_at')
    # op.drop_column('listings', 'urgent_expires_at')
    op.add_column('users', sa.Column('is_affiliate', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('referred_by_affiliate_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'affiliates', ['referred_by_affiliate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referred_by_affiliate_id')
    op.drop_column('users', 'is_affiliate')
    op.add_column('listings', sa.Column('urgent_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('boosted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('is_bold_title', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('is_urgent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_listings_is_urgent'), 'listings', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_listings_boosted_at'), 'listings', ['boosted_at'], unique=False)
    op.drop_index('ix_affiliate_clicks_date', table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_status'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_custom_slug'), table_name='affiliates')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
