"""Add escrow tables

Revision ID: 151b6337e72d
Revises: f9402d34a714
Create Date: 2026-02-16 20:14:49.515516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151b6337e72d'
down_revision: Union[str, Sequence[str], None] = 'f9402d34a714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrow_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escrow_transactions_buyer_id'), 'escrow_transactions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_listing_id'), 'escrow_transactions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_seller_id'), 'escrow_transactions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_status'), 'escrow_transactions', ['status'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['escrow_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    op.drop_index(op.f('ix_escrow_transactions_status'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_seller_id'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_listing_id'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_buyer_id'), table_name='escrow_transactions')
    op.drop_table('escrow_transactions')
    # ### end Alembic commands ###
