"""Initial migration

Revision ID: 177e4ab7e8a9
Revises: 
Create Date: 2026-02-12 11:23:03.206691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177e4ab7e8a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('click_url', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.JSON(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_slots_country_code'), 'ad_slots', ['country_code'], unique=False)
    op.create_index(op.f('ix_ad_slots_is_active'), 'ad_slots', ['is_active'], unique=False)
    op.create_index(op.f('ix_ad_slots_placement'), 'ad_slots', ['placement'], unique=False)
    op.create_index('ix_ad_slots_placement_country', 'ad_slots', ['placement', 'country_code', 'is_active'], unique=False)
    op.create_table('attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('placeholder', sa.JSON(), nullable=True),
    sa.Column('help_text', sa.JSON(), nullable=True),
    sa.Column('attribute_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('regex_pattern', sa.String(length=500), nullable=True),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_sortable', sa.Boolean(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_attribute_type'), 'attributes', ['attribute_type'], unique=False)
    op.create_index(op.f('ix_attributes_is_active'), 'attributes', ['is_active'], unique=False)
    op.create_index(op.f('ix_attributes_is_filterable'), 'attributes', ['is_filterable'], unique=False)
    op.create_index(op.f('ix_attributes_key'), 'attributes', ['key'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('country_scope', sa.String(length=5), nullable=True),
    sa.Column('is_pii_scrubbed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_country_scope'), 'audit_logs', ['country_scope'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.JSON(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_visible_on_home', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('inherit_enabled', sa.Boolean(), nullable=False),
    sa.Column('override_enabled', sa.Boolean(), nullable=True),
    sa.Column('inherit_countries', sa.Boolean(), nullable=False),
    sa.Column('override_countries', sa.JSON(), nullable=True),
    sa.Column('allowed_countries', sa.JSON(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_is_enabled'), 'categories', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_categories_module'), 'categories', ['module'], unique=False)
    op.create_index('ix_categories_module_enabled', 'categories', ['module', 'is_enabled', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_path'), 'categories', ['path'], unique=False)
    op.create_index('ix_categories_path_prefix', 'categories', ['path'], unique=False, postgresql_ops={'path': 'text_pattern_ops'})
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('default_currency', sa.String(length=5), nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('area_unit', sa.String(length=10), nullable=False),
    sa.Column('distance_unit', sa.String(length=10), nullable=False),
    sa.Column('weight_unit', sa.String(length=10), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('number_format', sa.String(length=20), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_phone', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_is_enabled'), 'countries', ['is_enabled'], unique=False)
    op.create_table('dealer_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('dealer_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('vat_tax_no', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_applications_country'), 'dealer_applications', ['country'], unique=False)
    op.create_index('ix_dealer_applications_country_status', 'dealer_applications', ['country', 'status'], unique=False)
    op.create_index(op.f('ix_dealer_applications_dealer_type'), 'dealer_applications', ['dealer_type'], unique=False)
    op.create_index(op.f('ix_dealer_applications_status'), 'dealer_applications', ['status'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('enabled_countries', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_is_enabled'), 'feature_flags', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_index(op.f('ix_feature_flags_scope'), 'feature_flags', ['scope'], unique=False)
    op.create_table('home_layout_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('block_order', sa.JSON(), nullable=False),
    sa.Column('mobile_nav_mode', sa.String(length=20), nullable=False),
    sa.Column('show_mega_menu', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_layout_settings_country_code'), 'home_layout_settings', ['country_code'], unique=True)
    op.create_table('home_showcase_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_home_showcase_country_active', 'home_showcase_items', ['country_code', 'is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_home_showcase_items_country_code'), 'home_showcase_items', ['country_code'], unique=False)
    op.create_index(op.f('ix_home_showcase_items_is_active'), 'home_showcase_items', ['is_active'], unique=False)
    op.create_table('home_special_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('label', sa.JSON(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('dealer_only', sa.Boolean(), nullable=False),
    sa.Column('premium_only', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_home_special_country_active', 'home_special_listings', ['country_code', 'is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_home_special_listings_country_code'), 'home_special_listings', ['country_code'], unique=False)
    op.create_index(op.f('ix_home_special_listings_is_active'), 'home_special_listings', ['is_active'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('customer_ref_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_vat_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('net_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gross_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate_snapshot', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('billing_snapshot', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_country'), 'invoices', ['country'], unique=False)
    op.create_index('ix_invoices_country_status', 'invoices', ['country', 'status'], unique=False)
    op.create_index('ix_invoices_customer', 'invoices', ['customer_type', 'customer_ref_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer_ref_id'), 'invoices', ['customer_ref_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_payment_idempotency_key'), 'invoices', ['payment_idempotency_key'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_stripe_payment_intent_id'), 'invoices', ['stripe_payment_intent_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=True),
    sa.Column('is_dealer_listing', sa.Boolean(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category_id'), 'listings', ['category_id'], unique=False)
    op.create_index(op.f('ix_listings_country'), 'listings', ['country'], unique=False)
    op.create_index('ix_listings_country_status', 'listings', ['country', 'status'], unique=False)
    op.create_index(op.f('ix_listings_dealer_id'), 'listings', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_listings_is_premium'), 'listings', ['is_premium'], unique=False)
    op.create_index('ix_listings_moderation', 'listings', ['status', 'country', 'module', 'created_at'], unique=False)
    op.create_index(op.f('ix_listings_module'), 'listings', ['module'], unique=False)
    op.create_index('ix_listings_module_status', 'listings', ['module', 'status'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_index(op.f('ix_listings_user_id'), 'listings', ['user_id'], unique=False)
    op.create_table('moderation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('bad_words_enabled', sa.Boolean(), nullable=False),
    sa.Column('bad_words_list', sa.JSON(), nullable=False),
    sa.Column('bad_words_mode', sa.String(length=20), nullable=False),
    sa.Column('min_images_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_images_count', sa.Integer(), nullable=False),
    sa.Column('price_sanity_enabled', sa.Boolean(), nullable=False),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('auto_approve_dealers', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_rules_country'), 'moderation_rules', ['country'], unique=True)
    op.create_table('premium_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('price_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('tax_category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_premium_products_active', 'premium_products', ['is_active', 'country'], unique=False)
    op.create_index(op.f('ix_premium_products_country'), 'premium_products', ['country'], unique=False)
    op.create_index('ix_premium_products_country_key', 'premium_products', ['country', 'key'], unique=True)
    op.create_index(op.f('ix_premium_products_is_active'), 'premium_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_premium_products_key'), 'premium_products', ['key'], unique=False)
    op.create_table('premium_ranking_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('premium_first', sa.Boolean(), nullable=False),
    sa.Column('weight_priority', sa.Integer(), nullable=False),
    sa.Column('weight_recency', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_ranking_rules_country'), 'premium_ranking_rules', ['country'], unique=True)
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_event_id'), 'stripe_events', ['event_id'], unique=True)
    op.create_table('stripe_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_key_env_key', sa.String(length=100), nullable=False),
    sa.Column('webhook_secret_env_key', sa.String(length=100), nullable=False),
    sa.Column('publishable_key', sa.String(length=255), nullable=True),
    sa.Column('account_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_settings_country'), 'stripe_settings', ['country'], unique=True)
    op.create_table('top_menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('badge', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('required_module', sa.String(length=50), nullable=True),
    sa.Column('allowed_countries', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_top_menu_items_enabled_sort', 'top_menu_items', ['is_enabled', 'sort_order'], unique=False)
    op.create_index(op.f('ix_top_menu_items_is_enabled'), 'top_menu_items', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_top_menu_items_key'), 'top_menu_items', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('country_scope', sa.JSON(), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('vat_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tax_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_rates_country'), 'vat_rates', ['country'], unique=False)
    op.create_index('ix_vat_rates_country_dates', 'vat_rates', ['country', 'valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('ix_vat_rates_is_active'), 'vat_rates', ['is_active'], unique=False)
    op.create_table('attribute_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attribute_options_attr_value', 'attribute_options', ['attribute_id', 'value'], unique=True)
    op.create_index(op.f('ix_attribute_options_attribute_id'), 'attribute_options', ['attribute_id'], unique=False)
    op.create_table('category_attribute_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('is_required_override', sa.Boolean(), nullable=True),
    sa.Column('display_order_override', sa.Integer(), nullable=True),
    sa.Column('inherit_to_children', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_attribute_map_attribute_id'), 'category_attribute_map', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_category_attribute_map_category_id'), 'category_attribute_map', ['category_id'], unique=False)
    op.create_index('ix_category_attribute_map_unique', 'category_attribute_map', ['category_id', 'attribute_id'], unique=True)
    op.create_table('category_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_translations_category_id'), 'category_translations', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_translations_language'), 'category_translations', ['language'], unique=False)
    op.create_index('ix_category_translations_unique', 'category_translations', ['category_id', 'language'], unique=True)
    op.create_table('dealers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('dealer_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('vat_tax_no', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_publish', sa.Boolean(), nullable=False),
    sa.Column('listing_limit', sa.Integer(), nullable=False),
    sa.Column('premium_limit', sa.Integer(), nullable=False),
    sa.Column('active_listing_count', sa.Integer(), nullable=False),
    sa.Column('total_listing_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['dealer_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_dealers_country'), 'dealers', ['country'], unique=False)
    op.create_index('ix_dealers_country_active', 'dealers', ['country', 'is_active'], unique=False)
    op.create_index(op.f('ix_dealers_dealer_type'), 'dealers', ['dealer_type'], unique=False)
    op.create_index(op.f('ix_dealers_is_active'), 'dealers', ['is_active'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_gross', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('listing_promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['premium_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_promotions_dates', 'listing_promotions', ['start_at', 'end_at'], unique=False)
    op.create_index(op.f('ix_listing_promotions_is_active'), 'listing_promotions', ['is_active'], unique=False)
    op.create_index('ix_listing_promotions_listing_active', 'listing_promotions', ['listing_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_listing_promotions_listing_id'), 'listing_promotions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_promotions_product_id'), 'listing_promotions', ['product_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_admin_id', sa.UUID(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_actions_action_type'), 'moderation_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_moderation_actions_actor_admin_id'), 'moderation_actions', ['actor_admin_id'], unique=False)
    op.create_index('ix_moderation_actions_listing_date', 'moderation_actions', ['listing_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_moderation_actions_listing_id'), 'moderation_actions', ['listing_id'], unique=False)
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_invoice_id'), 'payment_attempts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_payment_attempts_stripe_checkout_session_id'), 'payment_attempts', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_stripe_payment_intent_id'), 'payment_attempts', ['stripe_payment_intent_id'], unique=False)
    op.create_table('top_menu_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_countries', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['top_menu_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_menu_sections_menu_item_id'), 'top_menu_sections', ['menu_item_id'], unique=False)
    op.create_table('dealer_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_dealer', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_users_dealer_id'), 'dealer_users', ['dealer_id'], unique=False)
    op.create_index('ix_dealer_users_unique', 'dealer_users', ['dealer_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_dealer_users_user_id'), 'dealer_users', ['user_id'], unique=False)
    op.create_table('top_menu_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.JSON(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('target_ref', sa.String(length=500), nullable=False),
    sa.Column('open_new_tab', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('allowed_countries', sa.JSON(), nullable=False),
    sa.Column('is_view_all', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['top_menu_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_top_menu_links_section_id'), 'top_menu_links', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_menu_links_section_id'), table_name='top_menu_links')
    op.drop_table('top_menu_links')
    op.drop_index(op.f('ix_dealer_users_user_id'), table_name='dealer_users')
    op.drop_index('ix_dealer_users_unique', table_name='dealer_users')
    op.drop_index(op.f('ix_dealer_users_dealer_id'), table_name='dealer_users')
    op.drop_table('dealer_users')
    op.drop_index(op.f('ix_top_menu_sections_menu_item_id'), table_name='top_menu_sections')
    op.drop_table('top_menu_sections')
    op.drop_index(op.f('ix_payment_attempts_stripe_payment_intent_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_stripe_checkout_session_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_invoice_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_moderation_actions_listing_id'), table_name='moderation_actions')
    op.drop_index('ix_moderation_actions_listing_date', table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_actor_admin_id'), table_name='moderation_actions')
    op.drop_index(op.f('ix_moderation_actions_action_type'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('ix_listing_promotions_product_id'), table_name='listing_promotions')
    op.drop_index(op.f('ix_listing_promotions_listing_id'), table_name='listing_promotions')
    op.drop_index('ix_listing_promotions_listing_active', table_name='listing_promotions')
    op.drop_index(op.f('ix_listing_promotions_is_active'), table_name='listing_promotions')
    op.drop_index('ix_listing_promotions_dates', table_name='listing_promotions')
    op.drop_table('listing_promotions')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_dealers_is_active'), table_name='dealers')
    op.drop_index(op.f('ix_dealers_dealer_type'), table_name='dealers')
    op.drop_index('ix_dealers_country_active', table_name='dealers')
    op.drop_index(op.f('ix_dealers_country'), table_name='dealers')
    op.drop_table('dealers')
    op.drop_index('ix_category_translations_unique', table_name='category_translations')
    op.drop_index(op.f('ix_category_translations_language'), table_name='category_translations')
    op.drop_index(op.f('ix_category_translations_category_id'), table_name='category_translations')
    op.drop_table('category_translations')
    op.drop_index('ix_category_attribute_map_unique', table_name='category_attribute_map')
    op.drop_index(op.f('ix_category_attribute_map_category_id'), table_name='category_attribute_map')
    op.drop_index(op.f('ix_category_attribute_map_attribute_id'), table_name='category_attribute_map')
    op.drop_table('category_attribute_map')
    op.drop_index(op.f('ix_attribute_options_attribute_id'), table_name='attribute_options')
    op.drop_index('ix_attribute_options_attr_value', table_name='attribute_options')
    op.drop_table('attribute_options')
    op.drop_index(op.f('ix_vat_rates_is_active'), table_name='vat_rates')
    op.drop_index('ix_vat_rates_country_dates', table_name='vat_rates')
    op.drop_index(op.f('ix_vat_rates_country'), table_name='vat_rates')
    op.drop_table('vat_rates')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_top_menu_items_key'), table_name='top_menu_items')
    op.drop_index(op.f('ix_top_menu_items_is_enabled'), table_name='top_menu_items')
    op.drop_index('ix_top_menu_items_enabled_sort', table_name='top_menu_items')
    op.drop_table('top_menu_items')
    op.drop_index(op.f('ix_stripe_settings_country'), table_name='stripe_settings')
    op.drop_table('stripe_settings')
    op.drop_index(op.f('ix_stripe_events_event_id'), table_name='stripe_events')
    op.drop_table('stripe_events')
    op.drop_index(op.f('ix_premium_ranking_rules_country'), table_name='premium_ranking_rules')
    op.drop_table('premium_ranking_rules')
    op.drop_index(op.f('ix_premium_products_key'), table_name='premium_products')
    op.drop_index(op.f('ix_premium_products_is_active'), table_name='premium_products')
    op.drop_index('ix_premium_products_country_key', table_name='premium_products')
    op.drop_index(op.f('ix_premium_products_country'), table_name='premium_products')
    op.drop_index('ix_premium_products_active', table_name='premium_products')
    op.drop_table('premium_products')
    op.drop_index(op.f('ix_moderation_rules_country'), table_name='moderation_rules')
    op.drop_table('moderation_rules')
    op.drop_index(op.f('ix_listings_user_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index('ix_listings_module_status', table_name='listings')
    op.drop_index(op.f('ix_listings_module'), table_name='listings')
    op.drop_index('ix_listings_moderation', table_name='listings')
    op.drop_index(op.f('ix_listings_is_premium'), table_name='listings')
    op.drop_index(op.f('ix_listings_dealer_id'), table_name='listings')
    op.drop_index('ix_listings_country_status', table_name='listings')
    op.drop_index(op.f('ix_listings_country'), table_name='listings')
    op.drop_index(op.f('ix_listings_category_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_invoices_stripe_payment_intent_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_idempotency_key'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_ref_id'), table_name='invoices')
    op.drop_index('ix_invoices_customer', table_name='invoices')
    op.drop_index('ix_invoices_country_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_country'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_home_special_listings_is_active'), table_name='home_special_listings')
    op.drop_index(op.f('ix_home_special_listings_country_code'), table_name='home_special_listings')
    op.drop_index('ix_home_special_country_active', table_name='home_special_listings')
    op.drop_table('home_special_listings')
    op.drop_index(op.f('ix_home_showcase_items_is_active'), table_name='home_showcase_items')
    op.drop_index(op.f('ix_home_showcase_items_country_code'), table_name='home_showcase_items')
    op.drop_index('ix_home_showcase_country_active', table_name='home_showcase_items')
    op.drop_table('home_showcase_items')
    op.drop_index(op.f('ix_home_layout_settings_country_code'), table_name='home_layout_settings')
    op.drop_table('home_layout_settings')
    op.drop_index(op.f('ix_feature_flags_scope'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_is_enabled'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_dealer_applications_status'), table_name='dealer_applications')
    op.drop_index(op.f('ix_dealer_applications_dealer_type'), table_name='dealer_applications')
    op.drop_index('ix_dealer_applications_country_status', table_name='dealer_applications')
    op.drop_index(op.f('ix_dealer_applications_country'), table_name='dealer_applications')
    op.drop_table('dealer_applications')
    op.drop_index(op.f('ix_countries_is_enabled'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index('ix_categories_path_prefix', table_name='categories', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_index(op.f('ix_categories_path'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index('ix_categories_module_enabled', table_name='categories')
    op.drop_index(op.f('ix_categories_module'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_enabled'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_country_scope'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attributes_key'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_is_filterable'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_is_active'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_attribute_type'), table_name='attributes')
    op.drop_table('attributes')
    op.drop_index('ix_ad_slots_placement_country', table_name='ad_slots')
    op.drop_index(op.f('ix_ad_slots_placement'), table_name='ad_slots')
    op.drop_index(op.f('ix_ad_slots_is_active'), table_name='ad_slots')
    op.drop_index(op.f('ix_ad_slots_country_code'), table_name='ad_slots')
    op.drop_table('ad_slots')
    # ### end Alembic commands ###
