"""Add blog module

Revision ID: 31679d0b169d
Revises: p18_ledger_update
Create Date: 2026-02-16 16:56:27.347267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31679d0b169d'
down_revision: Union[str, Sequence[str], None] = 'p18_ledger_update'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_is_published'), 'blog_posts', ['is_published'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.drop_index(op.f('ix_listings_boosted_at'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_urgent'), table_name='listings')
    op.drop_column('listings', 'is_urgent')
    op.drop_column('listings', 'urgent_expires_at')
    op.drop_column('listings', 'is_bold_title')
    op.drop_column('listings', 'boosted_at')
    op.alter_column('reward_ledger', 'reward_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('reward_ledger_affiliate_id_fkey'), 'reward_ledger', type_='foreignkey')
    op.drop_column('reward_ledger', 'affiliate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reward_ledger', sa.Column('affiliate_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('reward_ledger_affiliate_id_fkey'), 'reward_ledger', 'affiliates', ['affiliate_id'], ['id'])
    op.alter_column('reward_ledger', 'reward_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('listings', sa.Column('boosted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('is_bold_title', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('urgent_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('is_urgent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_listings_is_urgent'), 'listings', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_listings_boosted_at'), 'listings', ['boosted_at'], unique=False)
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_is_published'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
