"""Add unique invoice constraint to subscription

Revision ID: 3403c9ea9d1a
Revises: df94532a3303
Create Date: 2026-02-12 14:04:46.237768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3403c9ea9d1a'
down_revision: Union[str, Sequence[str], None] = 'df94532a3303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
