"""Add referral tiers and user columns

Revision ID: 44ec5e23b2dc
Revises: p17_premium_fields
Create Date: 2026-02-16 16:11:41.792744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44ec5e23b2dc'
down_revision: Union[str, Sequence[str], None] = 'p17_premium_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('badge_icon', sa.String(length=100), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('min_count'),
    sa.UniqueConstraint('name')
    )
    # op.drop_index(op.f('ix_listings_boosted_at'), table_name='listings')
    # op.drop_index(op.f('ix_listings_is_urgent'), table_name='listings')
    # op.drop_column('listings', 'is_bold_title')
    # op.drop_column('listings', 'boosted_at')
    # op.drop_column('listings', 'is_urgent')
    # op.drop_column('listings', 'urgent_expires_at')
    op.add_column('users', sa.Column('referral_tier_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('referral_count_confirmed', sa.Integer(), server_default='0', nullable=False))
    op.create_foreign_key(None, 'users', 'referral_tiers', ['referral_tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referral_count_confirmed')
    op.drop_column('users', 'referral_tier_id')
    op.add_column('listings', sa.Column('urgent_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('is_urgent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('listings', sa.Column('boosted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listings', sa.Column('is_bold_title', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_listings_is_urgent'), 'listings', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_listings_boosted_at'), 'listings', ['boosted_at'], unique=False)
    op.drop_table('referral_tiers')
    # ### end Alembic commands ###
