"""Add index for expiry job

Revision ID: 4b5418a88ea4
Revises: 0e44994b5f92
Create Date: 2026-02-12 16:47:26.904122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5418a88ea4'
down_revision: Union[str, Sequence[str], None] = '0e44994b5f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dealer_subscriptions_status_end_at', 'dealer_subscriptions', ['status', 'end_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dealer_subscriptions_status_end_at', table_name='dealer_subscriptions')
    # ### end Alembic commands ###
