"""Add stripe fields to invoice

Revision ID: 58ddf8a32d45
Revises: 
Create Date: 2026-02-12 08:23:54.959004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ddf8a32d45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payment_idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('billing_snapshot', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_invoices_payment_idempotency_key'), 'invoices', ['payment_idempotency_key'], unique=True)
    op.create_index(op.f('ix_invoices_stripe_payment_intent_id'), 'invoices', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_stripe_payment_intent_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_idempotency_key'), table_name='invoices')
    op.drop_column('invoices', 'billing_snapshot')
    op.drop_column('invoices', 'stripe_payment_intent_id')
    op.drop_column('invoices', 'payment_idempotency_key')
    # ### end Alembic commands ###
