"""Add refund model and invoice fields

Revision ID: 6799b471fae5
Revises: 177e4ab7e8a9
Create Date: 2026-02-12 11:51:04.124134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6799b471fae5'
down_revision: Union[str, Sequence[str], None] = '177e4ab7e8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('refunded_total', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('refund_status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'refund_status')
    op.drop_column('invoices', 'refunded_total')
    # ### end Alembic commands ###
