"""Restore missing tables P25

Revision ID: 6f14b2f4dcb3
Revises: bccae351bcdd
Create Date: 2026-02-16 20:00:55.134422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f14b2f4dcb3'
down_revision: Union[str, Sequence[str], None] = 'bccae351bcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
