"""Add dealer packages and subscriptions

Revision ID: 6f816805117b
Revises: 34a3d781e692
Create Date: 2026-02-12 12:49:18.015225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f816805117b'
down_revision: Union[str, Sequence[str], None] = '34a3d781e692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('price_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('listing_limit', sa.Integer(), nullable=False),
    sa.Column('premium_quota', sa.Integer(), nullable=False),
    sa.Column('highlight_quota', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dealer_packages_country'), 'dealer_packages', ['country'], unique=False)
    op.create_index('ix_dealer_packages_country_active', 'dealer_packages', ['country', 'is_active'], unique=False)
    op.create_index(op.f('ix_dealer_packages_key'), 'dealer_packages', ['key'], unique=False)
    op.create_table('dealer_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remaining_listing_quota', sa.Integer(), nullable=False),
    sa.Column('remaining_premium_quota', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['dealer_packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id')
    )
    op.create_index(op.f('ix_dealer_subscriptions_dealer_id'), 'dealer_subscriptions', ['dealer_id'], unique=False)
    op.create_index(op.f('ix_dealer_subscriptions_end_at'), 'dealer_subscriptions', ['end_at'], unique=False)
    op.create_index(op.f('ix_dealer_subscriptions_status'), 'dealer_subscriptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dealer_subscriptions_status'), table_name='dealer_subscriptions')
    op.drop_index(op.f('ix_dealer_subscriptions_end_at'), table_name='dealer_subscriptions')
    op.drop_index(op.f('ix_dealer_subscriptions_dealer_id'), table_name='dealer_subscriptions')
    op.drop_table('dealer_subscriptions')
    op.drop_index(op.f('ix_dealer_packages_key'), table_name='dealer_packages')
    op.drop_index('ix_dealer_packages_country_active', table_name='dealer_packages')
    op.drop_index(op.f('ix_dealer_packages_country'), table_name='dealer_packages')
    op.drop_table('dealer_packages')
    # ### end Alembic commands ###
