"""Add stripe fields to invoice

Revision ID: 717de866a1ac
Revises: b4aa9f3a3e17
Create Date: 2026-02-16 11:03:36.720916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717de866a1ac'
down_revision: Union[str, Sequence[str], None] = 'b4aa9f3a3e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('payment_idempotency_key', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('refunded_total', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('refund_status', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('last_refund_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_invoices_stripe_payment_intent_id'), 'invoices', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_stripe_payment_intent_id'), table_name='invoices')
    op.drop_column('invoices', 'last_refund_at')
    op.drop_column('invoices', 'refunded_at')
    op.drop_column('invoices', 'refund_status')
    op.drop_column('invoices', 'refunded_total')
    op.drop_column('invoices', 'payment_idempotency_key')
    op.drop_column('invoices', 'stripe_payment_intent_id')
    # ### end Alembic commands ###
