"""Faz-U1 User Core Schema

Revision ID: 9a3aaec5ce28
Revises: e5471dc965cd
Create Date: 2026-02-16 20:45:21.920056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3aaec5ce28'
down_revision: Union[str, Sequence[str], None] = 'e5471dc965cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
