"""Add is_highlighted to conversations

Revision ID: 9f9e9c1bb40d
Revises: 1c2ba5052ea4
Create Date: 2026-02-16 20:09:03.630804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9e9c1bb40d'
down_revision: Union[str, Sequence[str], None] = '1c2ba5052ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
