"""Add user_devices table

Revision ID: a819a54e7f02
Revises: p19_feature_flag_config
Create Date: 2026-02-16 19:22:50.430116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a819a54e7f02'
down_revision: Union[str, Sequence[str], None] = 'p19_feature_flag_config'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_growth_events_country'), table_name='growth_events')
    op.create_index(op.f('ix_growth_events_country_code'), 'growth_events', ['country_code'], unique=False)
    op.drop_index(op.f('ix_listings_country_city_category'), table_name='listings')
    op.drop_index(op.f('ix_subscription_plans_country'), table_name='subscription_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscription_plans_country'), 'subscription_plans', ['country_code'], unique=False)
    op.create_index(op.f('ix_listings_country_city_category'), 'listings', ['country', 'city', 'category_id'], unique=False)
    op.drop_index(op.f('ix_growth_events_country_code'), table_name='growth_events')
    op.create_index(op.f('ix_growth_events_country'), 'growth_events', ['country_code'], unique=False)
    # ### end Alembic commands ###
