"""Add system_configs table

Revision ID: bccae351bcdd
Revises: efc0b8ac864d
Create Date: 2026-02-16 19:51:45.598809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bccae351bcdd'
down_revision: Union[str, Sequence[str], None] = 'efc0b8ac864d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exp_logs_name_variant'), table_name='experiment_logs')
    op.drop_index(op.f('ix_exp_logs_user_date'), table_name='experiment_logs')
    op.drop_index(op.f('ix_experiment_logs_user_id'), table_name='experiment_logs')
    op.drop_table('experiment_logs')
    op.drop_table('ml_models')
    op.drop_index(op.f('idx_user_device_token'), table_name='user_devices')
    op.drop_index(op.f('idx_user_device_user'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_ml_logs_model_date'), table_name='ml_prediction_logs')
    op.drop_index(op.f('ix_ml_prediction_logs_user_id'), table_name='ml_prediction_logs')
    op.drop_table('ml_prediction_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_prediction_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('top_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('execution_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ml_prediction_logs_pkey'))
    )
    op.create_index(op.f('ix_ml_prediction_logs_user_id'), 'ml_prediction_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_ml_logs_model_date'), 'ml_prediction_logs', ['model_version', 'created_at'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_rooted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_active_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_devices_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_devices_pkey')),
    sa.UniqueConstraint('token', name=op.f('user_devices_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_user_device_user'), 'user_devices', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_device_token'), 'user_devices', ['token'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('framework', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ml_models_pkey')),
    sa.UniqueConstraint('version', name=op.f('ml_models_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('experiment_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('experiment_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('variant', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('experiment_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('experiment_logs_pkey'))
    )
    op.create_index(op.f('ix_experiment_logs_user_id'), 'experiment_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_exp_logs_user_date'), 'experiment_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_exp_logs_name_variant'), 'experiment_logs', ['experiment_name', 'variant'], unique=False)
    # ### end Alembic commands ###
