"""Add missing monetization tables

Revision ID: cb79ce7dca3e
Revises: 4b5418a88ea7
Create Date: 2026-02-14 01:27:25.105290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb79ce7dca3e'
down_revision: Union[str, Sequence[str], None] = '4b5418a88ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_code'), 'subscription_plans', ['code'], unique=True)
    op.create_table('billing_customers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_billing_customers_stripe_customer_id'), 'billing_customers', ['stripe_customer_id'], unique=True)
    op.create_table('quota_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_usage_user_id'), 'quota_usage', ['user_id'], unique=False)
    op.create_index('ix_quota_usage_user_resource', 'quota_usage', ['user_id', 'resource'], unique=True)
    op.create_table('stripe_subscriptions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_subscriptions_current_period_end'), 'stripe_subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_status'), 'stripe_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_stripe_subscriptions_user_id'), 'stripe_subscriptions', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_end_at'), 'user_subscriptions', ['end_at'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('payment_attempt_id', sa.UUID(), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['payment_attempt_id'], ['payment_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_invoice_id'), 'refunds', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_refunds_stripe_refund_id'), 'refunds', ['stripe_refund_id'], unique=True)
    op.drop_index(op.f('ix_attribute_options_attr_value'), table_name='attribute_options')
    op.drop_constraint(op.f('attribute_options_attribute_id_fkey'), 'attribute_options', type_='foreignkey')
    op.create_foreign_key(None, 'attribute_options', 'attributes', ['attribute_id'], ['id'])
    op.alter_column('attributes', 'key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('attributes', 'attribute_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('attributes', 'is_variant',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_attributes_attribute_type'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_is_active'), table_name='attributes')
    op.drop_index(op.f('ix_attributes_is_filterable'), table_name='attributes')
    op.drop_column('attributes', 'max_value')
    op.drop_column('attributes', 'regex_pattern')
    op.drop_column('attributes', 'icon')
    op.drop_column('attributes', 'min_value')
    op.drop_column('attributes', 'placeholder')
    op.drop_column('attributes', 'help_text')
    op.drop_index(op.f('ix_category_attribute_map_unique'), table_name='category_attribute_map')
    op.drop_constraint(op.f('category_attribute_map_attribute_id_fkey'), 'category_attribute_map', type_='foreignkey')
    op.create_foreign_key(None, 'category_attribute_map', 'attributes', ['attribute_id'], ['id'])
    op.drop_column('category_attribute_map', 'display_order_override')
    op.add_column('invoice_items', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('invoice_items', 'description',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('invoice_items', 'line_tax')
    op.drop_column('invoice_items', 'currency')
    op.drop_column('invoice_items', 'price_config_version')
    op.drop_column('invoice_items', 'quantity')
    op.drop_column('invoice_items', 'line_net')
    op.drop_column('invoice_items', 'sort_order')
    op.drop_column('invoice_items', 'base_unit_price')
    op.drop_column('invoice_items', 'unit_price_net')
    op.drop_column('invoice_items', 'discount_amount')
    op.drop_column('invoice_items', 'country')
    op.drop_column('invoice_items', 'price_source')
    op.drop_column('invoice_items', 'applied_vat_rate')
    op.drop_column('invoice_items', 'created_at')
    op.drop_column('invoice_items', 'item_type')
    op.drop_column('invoice_items', 'ref_id')
    op.drop_column('invoice_items', 'line_gross')
    op.add_column('invoices', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('invoices', sa.Column('number', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('pdf_url', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_invoices_country'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_country_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_ref_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_no'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_payment_idempotency_key'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_stripe_payment_intent_id'), table_name='invoices')
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'invoices', ['number'])
    op.create_foreign_key(None, 'invoices', 'users', ['user_id'], ['id'])
    op.drop_column('invoices', 'refunded_at')
    op.drop_column('invoices', 'stripe_payment_intent_id')
    op.drop_column('invoices', 'country')
    op.drop_column('invoices', 'customer_address')
    op.drop_column('invoices', 'tax_total')
    op.drop_column('invoices', 'payment_idempotency_key')
    op.drop_column('invoices', 'customer_vat_no')
    op.drop_column('invoices', 'invoice_no')
    op.drop_column('invoices', 'billing_snapshot')
    op.drop_column('invoices', 'due_at')
    op.drop_column('invoices', 'refunded_total')
    op.drop_column('invoices', 'gross_total')
    op.drop_column('invoices', 'customer_type')
    op.drop_column('invoices', 'customer_ref_id')
    op.drop_column('invoices', 'net_total')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'customer_name')
    op.drop_column('invoices', 'cancelled_at')
    op.drop_column('invoices', 'tax_rate_snapshot')
    op.drop_column('invoices', 'customer_email')
    op.drop_column('invoices', 'issued_at')
    op.drop_column('invoices', 'refund_status')
    op.drop_column('invoices', 'notes')
    op.alter_column('listing_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_listing_attributes_attribute_id'), 'listing_attributes', ['attribute_id'], unique=False)
    op.add_column('stripe_events', sa.Column('type', sa.String(length=100), nullable=False))
    op.alter_column('stripe_events', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_stripe_events_event_id'), table_name='stripe_events')
    op.drop_column('stripe_events', 'event_id')
    op.drop_column('stripe_events', 'processing_error')
    op.drop_column('stripe_events', 'event_type')
    op.drop_index(op.f('ix_vat_rates_country'), table_name='vat_rates')
    op.drop_index(op.f('ix_vat_rates_country_dates'), table_name='vat_rates')
    op.drop_index(op.f('ix_vat_rates_is_active'), table_name='vat_rates')
    op.drop_column('vat_rates', 'description')
    op.drop_column('vat_rates', 'created_at')
    op.drop_column('vat_rates', 'updated_at')
    op.drop_column('vat_rates', 'valid_to')
    op.alter_column('vehicle_makes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('vehicle_makes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicle_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('vehicle_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicle_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('vehicle_makes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicle_makes', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('vat_rates', sa.Column('valid_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('vat_rates', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('vat_rates', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('vat_rates', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_vat_rates_is_active'), 'vat_rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_vat_rates_country_dates'), 'vat_rates', ['country', 'valid_from', 'valid_to'], unique=False)
    op.create_index(op.f('ix_vat_rates_country'), 'vat_rates', ['country'], unique=False)
    op.add_column('stripe_events', sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('stripe_events', sa.Column('processing_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('stripe_events', sa.Column('event_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_stripe_events_event_id'), 'stripe_events', ['event_id'], unique=True)
    op.alter_column('stripe_events', 'id',
               existing_type=sa.String(length=100),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('stripe_events', 'type')
    op.drop_index(op.f('ix_listing_attributes_attribute_id'), table_name='listing_attributes')
    op.alter_column('listing_attributes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('invoices', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('refund_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('customer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('tax_rate_snapshot', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('net_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('customer_ref_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('customer_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('gross_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('refunded_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('billing_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('invoice_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('customer_vat_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payment_idempotency_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('tax_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('customer_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('country', sa.VARCHAR(length=5), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('refunded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.create_index(op.f('ix_invoices_stripe_payment_intent_id'), 'invoices', ['stripe_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_payment_idempotency_key'), 'invoices', ['payment_idempotency_key'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_no'), 'invoices', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoices_customer_ref_id'), 'invoices', ['customer_ref_id'], unique=False)
    op.create_index(op.f('ix_invoices_customer'), 'invoices', ['customer_type', 'customer_ref_id'], unique=False)
    op.create_index(op.f('ix_invoices_country_status'), 'invoices', ['country', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_country'), 'invoices', ['country'], unique=False)
    op.drop_column('invoices', 'pdf_url')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'number')
    op.drop_column('invoices', 'user_id')
    op.add_column('invoice_items', sa.Column('line_gross', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('ref_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('invoice_items', sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('applied_vat_rate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('price_source', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('country', sa.VARCHAR(length=5), server_default=sa.text("'DE'::character varying"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('unit_price_net', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('base_unit_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('line_net', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('price_config_version', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoice_items', sa.Column('currency', sa.VARCHAR(length=5), server_default=sa.text("'EUR'::character varying"), autoincrement=False, nullable=False))
    op.add_column('invoice_items', sa.Column('line_tax', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_invoice_id_fkey'), 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_items', 'description',
               existing_type=sa.String(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('invoice_items', 'amount')
    op.add_column('category_attribute_map', sa.Column('display_order_override', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'category_attribute_map', type_='foreignkey')
    op.create_foreign_key(op.f('category_attribute_map_attribute_id_fkey'), 'category_attribute_map', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_category_attribute_map_unique'), 'category_attribute_map', ['category_id', 'attribute_id'], unique=True)
    op.add_column('attributes', sa.Column('help_text', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('placeholder', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('min_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('regex_pattern', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('attributes', sa.Column('max_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_attributes_is_filterable'), 'attributes', ['is_filterable'], unique=False)
    op.create_index(op.f('ix_attributes_is_active'), 'attributes', ['is_active'], unique=False)
    op.create_index(op.f('ix_attributes_attribute_type'), 'attributes', ['attribute_type'], unique=False)
    op.alter_column('attributes', 'is_variant',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('attributes', 'attribute_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('attributes', 'key',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'attribute_options', type_='foreignkey')
    op.create_foreign_key(op.f('attribute_options_attribute_id_fkey'), 'attribute_options', 'attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_attribute_options_attr_value'), 'attribute_options', ['attribute_id', 'value'], unique=True)
    op.drop_index(op.f('ix_refunds_stripe_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_invoice_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_end_at'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_user_id'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_status'), table_name='stripe_subscriptions')
    op.drop_index(op.f('ix_stripe_subscriptions_current_period_end'), table_name='stripe_subscriptions')
    op.drop_table('stripe_subscriptions')
    op.drop_index('ix_quota_usage_user_resource', table_name='quota_usage')
    op.drop_index(op.f('ix_quota_usage_user_id'), table_name='quota_usage')
    op.drop_table('quota_usage')
    op.drop_index(op.f('ix_billing_customers_stripe_customer_id'), table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_index(op.f('ix_subscription_plans_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
