"""Add legal_consents table

Revision ID: cd6c737c70f9
Revises: c9cd0de01284
Create Date: 2026-02-16 23:21:56.538339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6c737c70f9'
down_revision: Union[str, Sequence[str], None] = 'c9cd0de01284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_consent_user_doc', 'legal_consents', ['user_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_legal_consents_user_id'), 'legal_consents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_consents_user_id'), table_name='legal_consents')
    op.drop_index('ix_legal_consent_user_doc', table_name='legal_consents')
    op.drop_table('legal_consents')
    # ### end Alembic commands ###
