"""Add unique constraint for active subscription

Revision ID: df94532a3303
Revises: 6f816805117b
Create Date: 2026-02-12 13:59:27.692446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df94532a3303'
down_revision: Union[str, Sequence[str], None] = '6f816805117b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dealer_active_subscription', 'dealer_subscriptions', ['dealer_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dealer_active_subscription', table_name='dealer_subscriptions', postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###
