"""Add growth events

Revision ID: e0a5c6256c36
Revises: 31679d0b169d
Create Date: 2026-02-16 17:22:54.620851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a5c6256c36'
down_revision: Union[str, Sequence[str], None] = '31679d0b169d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('affiliate_id', sa.UUID(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_events_affiliate_id'), 'growth_events', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_growth_events_event_type'), 'growth_events', ['event_type'], unique=False)
    op.create_index('ix_growth_events_type_date', 'growth_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_growth_events_user_id'), 'growth_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_growth_events_user_id'), table_name='growth_events')
    op.drop_index('ix_growth_events_type_date', table_name='growth_events')
    op.drop_index(op.f('ix_growth_events_event_type'), table_name='growth_events')
    op.drop_index(op.f('ix_growth_events_affiliate_id'), table_name='growth_events')
    op.drop_table('growth_events')
    # ### end Alembic commands ###
