"""Add payment models

Revision ID: f659c3b863c4
Revises: 58ddf8a32d45
Create Date: 2026-02-12 08:43:09.705811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f659c3b863c4'
down_revision: Union[str, Sequence[str], None] = '58ddf8a32d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_event_id'), 'stripe_events', ['event_id'], unique=True)
    op.create_table('stripe_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_key_env_key', sa.String(length=100), nullable=False),
    sa.Column('webhook_secret_env_key', sa.String(length=100), nullable=False),
    sa.Column('publishable_key', sa.String(length=255), nullable=True),
    sa.Column('account_mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_settings_country'), 'stripe_settings', ['country'], unique=True)
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('amount_gross', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_code', sa.String(length=50), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_invoice_id'), 'payment_attempts', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_status'), 'payment_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_payment_attempts_stripe_checkout_session_id'), 'payment_attempts', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_payment_attempts_stripe_payment_intent_id'), 'payment_attempts', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_attempts_stripe_payment_intent_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_stripe_checkout_session_id'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_status'), table_name='payment_attempts')
    op.drop_index(op.f('ix_payment_attempts_invoice_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_stripe_settings_country'), table_name='stripe_settings')
    op.drop_table('stripe_settings')
    op.drop_index(op.f('ix_stripe_events_event_id'), table_name='stripe_events')
    op.drop_table('stripe_events')
    # ### end Alembic commands ###
