"""Add abuse control fields

Revision ID: f83f2eddec93
Revises: e0a5c6256c36
Create Date: 2026-02-16 17:26:18.098309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83f2eddec93'
down_revision: Union[str, Sequence[str], None] = 'e0a5c6256c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('risk_score', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('device_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_device_hash'), 'users', ['device_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_hash'), table_name='users')
    op.drop_column('users', 'device_hash')
    op.drop_column('affiliates', 'risk_score')
    # ### end Alembic commands ###
