"""Add user_reviews and rating fields

Revision ID: fc55662ba637
Revises: 9f9e9c1bb40d
Create Date: 2026-02-16 20:13:07.439106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc55662ba637'
down_revision: Union[str, Sequence[str], None] = '9f9e9c1bb40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_user_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['reviewed_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reviewer_id', 'listing_id', name='uq_review_interaction')
    )
    op.create_index(op.f('ix_user_reviews_listing_id'), 'user_reviews', ['listing_id'], unique=False)
    op.create_index(op.f('ix_user_reviews_reviewed_user_id'), 'user_reviews', ['reviewed_user_id'], unique=False)
    op.create_index(op.f('ix_user_reviews_reviewer_id'), 'user_reviews', ['reviewer_id'], unique=False)
    op.add_column('conversations', sa.Column('is_highlighted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_highlighted')
    op.drop_index(op.f('ix_user_reviews_reviewer_id'), table_name='user_reviews')
    op.drop_index(op.f('ix_user_reviews_reviewed_user_id'), table_name='user_reviews')
    op.drop_index(op.f('ix_user_reviews_listing_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    # ### end Alembic commands ###
